### ISSUE TITLE
GUI shows as a plain white screen (doesn't load) on Mac

### ISSUE THREAD

**Issue by pietrog30** [OpenBCI/OpenBCI_GUI#1001]
## Problem

I just purchased the Ultracortex Mark IV Setup. I just downloaded the GUI on my Mac, but after launching it, it just shows a white page. I tried removing and reinstalling the application like 4 times and restarting the Mac as well. Nothing seems to help, and I am unable to view the brain data.

<img width="1030" alt="Screen Shot 2021-09-28 at 1 32 47 PM" src="https://user-images.githubusercontent.com/26072858/135167565-5e5a7cec-c430-450b-9cdf-e8b9aa3221c0.png">

## Expected 

The GUI should load as it does in any tutorial I've seen.

## Operating System and Version

macOS Big Sur - Version 11.6

## GUI Version

Version 5 (5.0.6)

## Running standalone app

Running the downloaded app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
Deploying fix that has passed testing tonight!
