### ISSUE TITLE
The type Serial is ambiguous.

### ISSUE THREAD

**Issue by cfausn** [OpenBCI/OpenBCI_GUI#1025]
## Problem

Issue starting the OpenBCI GUI with the latest version of Processing v4.0b3. When pressing "start," the following error occurs. **I resolved the issue by downgrading Processing to v3.5.4, but wanted to make sure ya'll were aware of the issue.**

## Expected 

Should start the OpenBCI GUI on pressing start.

## Operating System and Version

Windows 10

## GUI Version

v5.0.9

## Running standalone app

Running on Processing 4.0b3

## Console Log

![image](https://user-images.githubusercontent.com/12140396/150578750-4bbcda9c-a883-4019-a88d-a3768bdb54eb.png)

**Comment by retiutut** [comment]
@cfausn There is an open PR to bump the GUI to finally use Processing 4. I have linked this issue. Thanks for testing!

**Comment by retiutut** [comment]
@cfausn The problem here is that Processing 4 beta 2 uses Java 11, while beta 3 goes all the way to Java 17 and has not been tested.

**Comment by retiutut** [comment]
Replicated and Fixed!

**Comment by retiutut** [comment]
I am now in the process of downgrading our work on 5.1.0 back to Processing 3. We had severe issues on Windows with the new Popup FilterUI Window when resizing and clicking inside this new window.

**Comment by retiutut** [comment]
We will also need to explicitly say here on Github and the Docs that we need to use Processing 3.

Processing 4 is in beta as of today, but seems to have more issues than solutions for now.
