### ISSUE TITLE
Apply smoothing by default

### ISSUE THREAD

**Issue by ThreeForm** [OpenBCI/OpenBCI_GUI#1026]
## Problem

Inconsistent waveform update in GUI (known issue) when COM driver latency not changed from 16ms to 1ms and smoothing option is not on.

## Expected 

The software smoothing option should be on by default since that mostly fixes the problem. A "pro-tips" pop-up the first time the user starts the software can alert them to the fact they can shave a few hundred ms off the total latency (in addition to fixing the smoothness problem) by changing the latency setting.

## Operating System and Version

Win10

## GUI Version

5.09

## Running standalone app

downloaded binary

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
Since there is no way to confirm that the FTDI fix has been done via code, this would then be a hassle to turn off every time.

This is a "Session Setting" that applies only to cyton, which means it doesn't really belong as a "GUI-wide setting. Session settings are no longer loaded by default.

This is almost a lose-lose situation.

**Comment by retiutut** [comment]
This does help Mac users and beginning users the most. I think this can be done if we increase the communication about the FTDI fix in the GUI, Docs, and maybe also BrainFlow documentation.

**Comment by retiutut** [comment]
![Screen Shot 2022-03-07 at 7 14 35 PM](https://user-images.githubusercontent.com/25914123/157146179-bcd4548c-67bc-4602-bec2-eb3bf96a8c8b.png)

**Comment by retiutut** [comment]
![Screen Shot 2022-03-11 at 5 40 47 PM](https://user-images.githubusercontent.com/25914123/157990192-4f505d63-1fc3-464d-a844-95a533b9d74d.png)
