### ISSUE TITLE
Cyton: EEG amplitudes are different in GUI and exported bdf file (scaling issues?) 

### ISSUE THREAD

**Issue by LeXing1105** [OpenBCI/OpenBCI_GUI#1078]
## Problem

When I used the Cyton board to record an EEG/ECG signal, the signal amplitude in the OpenBCI GUI looks correct in the normal range, but when I exported the raw data into BDF or TXT file formats, the amplitude becomes very low (lower than in GUI), which is not correct. What caused these issues? Are there any scaling issues?  (wrong gain values? or similar)

In the GUI, I know there is a notch filter and a bandpass filter applied, In exported data, no processing applied, but the signal amplitudes differ too much!

The examples attached show the problem. 
EEG: in GUI and MatLab are the same recording,
ECG: in GUI and MATLAB are the same recording;

![EEG_GUI](https://user-images.githubusercontent.com/73104004/185919008-a7343064-c416-413d-b953-f26196a6f4c2.png)
![ECG_GUI](https://user-images.githubusercontent.com/73104004/185919009-1689e3b3-5cf6-4260-a632-cfa7d2f37fe8.png)
![EEG-matlab](https://user-images.githubusercontent.com/73104004/185919013-7084e0b5-8851-4490-b5a1-ced385d4428f.png)
![ECG-matlab](https://user-images.githubusercontent.com/73104004/185919018-af9c27cb-e8d9-43c0-b4d5-a6fcbd11f7fe.png)

## Expected 

I want to know what caused this issue if there is something you already know, please help me foe debugging, if this is a new bug (amplification/scaling issue in your export code), please fix it and let me know what is the scaling factor, how to recover the amplitude back to the correct one.

## Operating System and Version

Windows

## GUI Version

GUI Version v5.1.0

## Running standalone app

check data in MATLAB EEGlab toolbox

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here

**Comment by retiutut** [comment]
Everything looks fine. The values in the GUI are in uVrms (microvolts root mean square).

**Comment by retiutut** [comment]
@LeXing1105 Did you change the gain in the Hardware Settings?

**Comment by LeXing1105** [comment]
@retiutut Thank you for your reply! The GUI figures may not be very clear in the post. For example, in the ECG signal, the 2nd channel has a ±400μV window, the ECG=93.3μVrms, but the peak value should be at around 400μV, right？ but in the Matlab plot, the exported ECG signal (from the same recording) only has a 10μV (between the baseline to the peak value), maybe the unit here is not μV, so it looks wired. The gain in GUI hardware settings is set as x24, as default.

The EEG signal and ECG have the same issue. What do you think the problem is?

**Comment by retiutut** [comment]
It’s not very fair to say the values in the GUI are wrong without mentioning the units in MATLAB. Thanks for opening this issue but I still conclude there is nothing wrong.

**Comment by LeXing1105** [comment]
@retiutut OK, fine, the MATLAB figures just plotted the raw exported data, without any processing. I am also not sure what the unit is. Can you please tell me what the unit should be from the raw exported BDF data?

**Comment by retiutut** [comment]
The values stored to CSV and BDF are microvolts.

**Comment by retiutut** [comment]
From DataLogger.pde

```
    private void saveNewData() {
        //If data is available, save to playback file...
        if(!settings.isLogFileOpen()) {
            return;
        }

        double[][] newData = currentBoard.getFrameData();

        switch (outputDataSource) {
            case OUTPUT_SOURCE_ODF:
                fileWriterODF.append(newData);
                break;
            case OUTPUT_SOURCE_BDF:
                fileWriterBDF.writeRawData_dataPacket(newData);
                break;
            case OUTPUT_SOURCE_NONE:
            default:
                // Do nothing...
                break;
        }
    }
    ```
    
    Here we can see we simply get data between the last frame and the current frame, and this is passed either to CSV or BDF writer class, and is unfiltered.
