### ISSUE TITLE
Error starting Streaming Board from external BrainFlow process

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#1102]
## Problem

This is an advanced feature. Discovered this bug while writing QA tests. https://github.com/OpenBCI/OpenBCI_GUI/issues/1100#issuecomment-1382641371

This could be a simple version mismatch issue. Tried 5.5.0 in GUI and 5.6.0 in external process. Received `INVALID_ARGUMENTS_ERROR` in the GUI. Might be an easy fix since the specifications for this feature may have changed since it was originally implemented.

## Expected 

Connect to any OpenBCI board using an external app/process/script using any BrainFlow binding and visualize the data in the GUI using the StreamingBoard data mode.

## Operating System and Version

N/A

## GUI Version

5.1.1-alpha.1

## Running standalone app

Running from Processing

## Type of OpenBCI Board

All OpenBCI boards, but found this using BrainFlow's Synthetic Board

## Are you using a WiFi Shield?

No

## Console Log

See linked comment.  https://github.com/OpenBCI/OpenBCI_GUI/issues/1100#issuecomment-1382641371

[Console_2023-01-13_19-36-57.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/10416400/Console_2023-01-13_19-36-57.txt)

**Comment by philippitts** [comment]
At first glance it looks like the params argument to the `BoardShim` constructor is incorrect. Maybe check https://brainflow.readthedocs.io/en/stable/SupportedBoards.html? You need to assign the `master_board` parameter to the board ID of the device being played back.
