### ISSUE TITLE
GUI will not load past startup

### ISSUE THREAD

**Issue by einelson** [OpenBCI/OpenBCI_GUI#1109]
## Problem

Upon running the GUI for the first time the app will not get past the startup screen. In the screenshot attached below you can see that the app unpackaged the libs and dlls, but nothing beyond that.

## Expected 

I expected after a short wait for the screen to advance to the GUI

## Operating System and Version

Windows 11
Version 22H2
OS build: 22621.1105

## GUI Version

v5.1.0

## Are you running the downloaded app or from Processing/VSCode?

The downloaded app

## Type of OpenBCI Board

Ganglion

## Console Log and Screenshots

![image](https://user-images.githubusercontent.com/36721383/214173788-c519430c-3d57-4d66-89af-68e52c65af81.png)

**Comment by retiutut** [comment]
Does this computer have an Audio Output specified?

**Comment by retiutut** [comment]
Same reason as #1086 but happening on Windows. This is a rare issue.

**Comment by retiutut** [comment]
Ok missed this part on first read:

```
So I switched back to windows, plugged (bluetooth-ed) my headphones in and viola! The app started right up.
```

Let's see if we can try/catch this.

**Comment by retiutut** [comment]
Replicated on Windows by manually disabling all Audio Devices.

**Comment by retiutut** [comment]
![Screenshot 2023-01-31 211106](https://user-images.githubusercontent.com/25914123/215936395-eaf371d6-9a05-4792-aacb-32b3b2059c20.png)

Thankfully the exception is exposed at our level so we are able to catch this! Will then store the fact that Audio Device is not available and output an error when this feature in the Focus widget is pressed.

**Comment by retiutut** [comment]
Fun fact. We cannot disable the included audio device on a Mac without using some wizardry. You can remove other third party audio devices, but there is always an included "Built-in Output". Probably for such reasons as this and to allow the system to do beeps and boops.

**Comment by einelson** [comment]
Hey! Thanks for the reply! I don't believe my desktop had an audio port specified by default.

Thanks for the quick fix!
