### ISSUE TITLE
Upgrade to Processing 4

### ISSUE THREAD

**Issue by philippitts** [OpenBCI/OpenBCI_GUI#1111]
## Problem

Processing 3 is no longer supported and several workarounds are needed in order to continue supporting modern systems. We should upgrade to Processing 4 or enumerate any obstacles that prevent us from doing so.

## Expected 

The application will work when run from Processing 4.

**Comment by CGrassin** [comment]
I needed OpenBCI to run on Processing 4.2, so I did a very quick port myself. As far as I can tell, it is extremely straightforward to make it work. The only things I had to fix were a few function calls like the control P5 "setDescription()" method that seems to have been removed.
I can do a PR if that helps, but I did not perform any deep tests, I just used it for my own needs.

**Comment by retiutut** [comment]
Comments on Processing 4.2 + Windows:
- There's still a very serious error happening when resizing and trying to close child windows (Console Log and Filter UI pop-outs)
- Until this is fixed we can still move to Processing 4 by making these child windows a fixed height/width and making the non-resizeable
