### ISSUE TITLE
Custom location selection for saving recording in OpenBCI GUI is not saving generated file in the same location.

### ISSUE THREAD

**Issue by black** [OpenBCI/OpenBCI_GUI#1122]
## Problem

When selecting the custom location for saving recording from OpenBCI GUI, the generated files (BrainFlow csv file and OpenBCI Playback  txt file)  are not saving in the same location.  Recorded data in Brainflow file was getting saved in the custom location on the computer but OpenBCI playback file was getting save in the default location as mentioned in the documentation - (USER]/Documents/OpenBCI_GUI/Recordings/)

## Expected 

When selecting the custom location for saving recordings, the generated files (BrainFlow csv file and OpenBCI Playback  txt file) should save in the same location. 

## Operating System and Version

Windows 11 22H2, OS Build 22621.1194

## GUI Version

OpenBCI_GUI 5.1.0 , May 31, 2022

## Are you running the downloaded app or from Processing/VSCode?

The downloaded app or compiling and running the code.

## Type of OpenBCI Board

Cyton/Cyton+Daisy/

**Comment by retiutut** [comment]
Both the BrainFlow CSV and OpenBCI CSV are saved in the folder name that is specified in the Session Data box in the control panel.
