### ISSUE TITLE
JavaScript error: Not compatable USB Bluetooth 4.0

### ISSUE THREAD

**Issue by sergeiPP** [OpenBCI/OpenBCI_GUI#116]
![image](https://cloud.githubusercontent.com/assets/25400424/22395593/12837546-e554-11e6-9a26-89abaef92dee.png)

I don't use any bluetooth dongle just open bci dongle. GUI works fine I just see this message.

**Comment by wezzix** [comment]
Did you plug it directly into your computer, not through a USB hub or other extension?

**Comment by sergeiPP** [comment]
Directly. The same error when it removed. Error message appears during startup. Before "start system" pressed.

**Comment by aj-ptw** [comment]
Closing this because duplicate of #111

**Comment by aj-ptw** [comment]
There is a patch for this coming
