### ISSUE TITLE
GUI freezes at start on Mac OS Sierra 10.12.3

### ISSUE THREAD

**Issue by compmonks** [OpenBCI/OpenBCI_GUI#118]
Hi all,
the gui freezes when system starts.
connection with the dongle and the cyton is up.

16channels cyton +daisy
GUI mac version 2.0.0
OS Mac sierra 10.12.3
ftdi driver 2.3

should I downgrade my OS or is there a quick fix?
cheers

**Comment by aj-ptw** [comment]
Where are you launching the Application from? What directory is it in?

**Comment by compmonks** [comment]
from the mac app directory

**Comment by aj-ptw** [comment]
Can you please screen shot

**Comment by compmonks** [comment]
<img width="1027" alt="screen shot 2017-02-02 at 14 53 27" src="https://cloud.githubusercontent.com/assets/3306992/22552039/886f546c-e957-11e6-9cfb-2681667e9542.png">

**Comment by compmonks** [comment]
<img width="1027" alt="screen shot 2017-02-02 at 14 55 35" src="https://cloud.githubusercontent.com/assets/3306992/22552082/afb4dc9a-e957-11e6-8c93-4a0791386e2e.png">

**Comment by aj-ptw** [comment]
Sorry I meant of your application folder, I want to see if the OpenBCI GUI app is within another folder in your application for or not.

**Comment by compmonks** [comment]
here you go.
I have also tried with the application outside of the openbci folder but the results are similar

<img width="487" alt="screen shot 2017-02-02 at 15 26 39" src="https://cloud.githubusercontent.com/assets/3306992/22553255/553a39ae-e95c-11e6-837d-a1339df1cdf1.png">

**Comment by aj-ptw** [comment]
> outside of the openbci folder

Like this?
![screen shot 2017-02-02 at 9 51 33 am](https://cloud.githubusercontent.com/assets/11437469/22554175/34cc7530-e92d-11e6-82c0-a8b525df1a21.png)

**Comment by compmonks** [comment]
yes.
I finally got it working with the application outside the openbci folder but with keeping the saveddata folder inside (see below).
<img width="579" alt="screen shot 2017-02-02 at 16 04 11" src="https://cloud.githubusercontent.com/assets/3306992/22554679/4723ac6a-e961-11e6-9c9c-821cafc53d77.png">

**Comment by aj-ptw** [comment]
@compmonks could you please elaborate more? 

Did you see this line:
http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-using-the-openbci-gui-as-a-standalone-application-install-the-application

specifically: _**Note:** for Mac OS Sierra, you must put the application in your /Applications folder in order for it to work properly._

**Comment by compmonks** [comment]
@aj-ptw thank you
yes I saw the previous indications in the tutorial.
My mistake was to put both the application and the "SavedData" folder directly in the applications directory. In my case it seems that it works only if the "SavedData" folder stays inside the "OpenBCI_GUI_200_MACOSX" folder.
