### ISSUE TITLE
Rename UDP type field of EMG Joystick

### ISSUE THREAD

**Issue by isaacplotkin** [OpenBCI/OpenBCI_GUI#1184]
## Problem

Christian brought up a good point that the type field in the UDP packet for the EMG joystick is named "DroneControl", but it would more sense to have a more generic name since the EMG joystick can be used to control more than just a drone.

## Expected 

Rename this UDP packet type to "Joystick" or "EMGJoystick"

## GUI Version

v5.2.1

**Comment by retiutut** [comment]
In this version of the GUI, it is already like this.

```
} else if (this.protocol.equals("UDP")) {
            StringBuilder output = new StringBuilder("{\"type\":\"emgJoystick\",\"data\":[");
```
