### ISSUE TITLE
No Data Sent over Serial Connection

### ISSUE THREAD

**Issue by rhys151** [OpenBCI/OpenBCI_GUI#1208]
## Problem
I am trying to follow this [instructable](https://www.instructables.com/Send-Focus-Data-From-OpenBCI-GUI-to-Arduino/) to send focus data from the GUI over serial connection to an Arduino. I open up the GUI as admin using "synthetic" data , connect the Arduino my computer with usb on COM5, and set up the focus and networking widgets. The networking widget is set to COM5 as well, with the correct baud rate. 

The issue is that even once I click "start serial stream," the Arduino doesn't register any incoming data. Serial.available() is always a 0. In the console it says "Networking Serial, Focus error - null". Has anyone had this problem or know how to fix it?

## Operating System and Version
Windows 23H2 22631.3155

## GUI Version
v5.2.2

## Are you running the downloaded app or from Processing/VSCode?
The downloaded app.

## Type of OpenBCI Board
Cyton+Daisy

## Console Log and Screenshots
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/117540376/1e3dad83-ca72-4c27-a6f8-95fb39fd47cf)

**Comment by retiutut** [comment]
Mentioned as resolved in https://openbci.com/forum/index.php?p=/discussion/comment/20168#Comment_20168
