### ISSUE TITLE
How to duplicate Focus widget/send data concentration relax at same time

### ISSUE THREAD

**Issue by voskovka** [OpenBCI/OpenBCI_GUI#1215]
I'm using OpenBCI with touchdesigner. And I want to use data about concentration and relaxation from FocusWidget at same in Touchdesigner. But I can only open one focuswidget. I want to have interactive installation, when you can choose relaxation or concentration mode by pressing the button. 

I tried to to figure out how it analyze the data or I tried duplicated the focuswidget and create new but it didnt work. Im really hopeless, I need it for my semestral work

**Comment by retiutut** [comment]
https://github.com/brainflow-dev/brainflow/blob/master/cpp_package/examples/ml/src/dyn_lib_test/dyn_lib_test.cpp

Concentration and Relaxation are just reciprocals, and they are called from BrainFlow.
