### ISSUE TITLE
Visualizers not working for Ganglion

### ISSUE THREAD

**Issue by matthew-groth** [OpenBCI/OpenBCI_GUI#123]
I learned how to use the Processing version and looked through the code. Now I understand that visualizers are purposefully turned off for the Ganglion. I turned them on to see what would happen, and they did not work. I'm guessing that this is because OpenBCI GUI doesn't officially support Ganglion yet? Or is there a way I could get visualizers to work?

**Comment by aj-ptw** [comment]
@matthew-groth please upload screen shots. I'm not sure which visualizers you are talking about.

**Comment by matthew-groth** [comment]
Here is what my GUI looks like after initialization:

![image](https://cloud.githubusercontent.com/assets/12831489/22708384/11754650-ed44-11e6-8aff-2378978dddc6.png)

Here is the output, where the last relevant line is "OpenBCI_GUI: initSystem: -- Init 4 -- 14159"

![image](https://cloud.githubusercontent.com/assets/12831489/22708424/324cec20-ed44-11e6-86de-da9057897925.png)

OpenBCI_GUI does not go into POSTINIT mode if datasource is Ganglion:
`      if (eegDataSource != DATASOURCE_GANGLION && eegDataSource != DATASOURCE_NORMAL_W_AUX) {
        systemMode = SYSTEMMODE_POSTINIT; //tell system it's ok to leave control panel and start interfacing GUI
      }`

So I removed the ganglion check so I could see the graphs. But even after starting data stream, nothing happens:

![image](https://cloud.githubusercontent.com/assets/12831489/22709048/7190ac3a-ed46-11e6-9edb-18535c0577ed.png)

And the last relevant printed output in case it is useful: 

![image](https://cloud.githubusercontent.com/assets/12831489/22709057/7e121020-ed46-11e6-8d45-3479d2355ec8.png)

**Comment by aj-ptw** [comment]
Hey there is some connection issue going on here because you can see the message:
```bash
OpenBCI_Ganglion: parseMessage: default: k,400,;
```
because if you checkout the HUB docs https://github.com/OpenBCI/Docs/blob/master/OpenBCI%20Software/07-OpenBCI_Hub.md#command it's a standard error response code. It means your not able to connect to the Ganglion. That's why there is a freeze.

Please post the output printed **before** that last screen shot

**Comment by matthew-groth** [comment]
Solved it! Thanks to pushtheworld on [my forum post](http://openbci.com/forum/index.php?p=/discussion/comment/5522#Comment_5522) for telling me all I had to do was remove the dongle.

I got signal!
![image](https://cloud.githubusercontent.com/assets/12831489/22714627/679b922a-ed5b-11e6-910c-1a9f0e8ce3c6.png)

I am going to make a couple of pushes to help other Mac users avoid this issue.

**Comment by aj-ptw** [comment]
@pushtheworld saves the day! woo ;)
