### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by dado93** [OpenBCI/OpenBCI_GUI#126]
Hi,

I'm experiencing very high CPU usage with the OpenBCI GUI v2 (and also with the custom software that I developed in Processing to interface with the OpenBCI boards): the %CPU reaches on average 100%, with peaks well above it (see attached figure). 

My hardware specs are:

- OpenBCI 32 - bit with custom v2 firmware (the only difference with the default firmware is the analog reading from an analog PIN)

- OpenBCI Ganglion Board 

- Processing 3.2.1

- Mac OS 10.11.6

<img width="320" alt="schermata_2017_02_09_alle_10_43_33" src="https://cloud.githubusercontent.com/assets/25668758/22794499/02e5b61c-eeb9-11e6-9bf8-2f208cf3c41d.png">

**Comment by aj-ptw** [comment]
Try changing the layout and not using the headplot

**Comment by dado93** [comment]
I changed the layout: with the time series only, it is about 50% when not streaming, 90% when streaming.

<img width="1280" alt="schermata 2017-02-09 alle 11 20 32" src="https://cloud.githubusercontent.com/assets/25668758/22794754/ebc57e1c-eeb9-11e6-861b-1dc79a32f123.png">
<img width="1280" alt="schermata 2017-02-09 alle 11 19 47" src="https://cloud.githubusercontent.com/assets/25668758/22794757/ed933950-eeb9-11e6-9159-c7f1d10c801b.png">

**Comment by dado93** [comment]
Here is the hardware info of my computer:
  Model:	MacBook Pro
  Processor:	Intel Core i7 dual core 3.1 GHz
  Velocità processore:	3,1 GHz
  RAM:	8 GB

**Comment by aj-ptw** [comment]
@dado93 hi there, sorry for the delayed response. 
This is most likely due to this line https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/OpenBCI_GUI.pde#L122 or 
```java
final int nPointsPerUpdate = 10;
```

Which will cause performance issues. Lowering this number results in less CPU usage.

**Comment by aj-ptw** [comment]
Hi this is fixed in the upcoming v3 GUI with variable frame rates and not loading the head plot by default. also we introduced multiprocessing to do the data collection in a whole different process.
