### ISSUE TITLE
BLE on Mac

### ISSUE THREAD

**Issue by HMBTECP** [OpenBCI/OpenBCI_GUI#128]
i have problems connecting the OpenBCI Ganglion to the GUI.
the Bluetooth is activated and yet the the application give me code 412Error Turn Bluetooth on.
and i can't find the board.
and if i use a csr bluetooth dongle i can find the board but i can't start the system.

**Comment by aj-ptw** [comment]
What OS?

**Comment by HMBTECP** [comment]
MacOS Sierra
10.12.2

**Comment by aj-ptw** [comment]
@HMBTECP this sounds super frustrating, Sierra has been causing headaches around the world with their new permissions and such. Would you mind reviewing the [Ganglion Getting Started Guide](http://docs.openbci.com/Tutorials/02-Ganglion_Getting%20Started_Guide#ganglion-getting-started-guide-downloadrun-the-openbci-gui-on-macos) in the tutorials? With Sierra, the location of the GUI application is extremely important, see this excerpt from the guide:

> NOTE: If you are using a Mac with macOS Sierra, you MUST move the OpenBCI_GUI.app into your Applications folder. You also need to change your Security & Privacy settings to allow apps from Anywhere. Go to the end of this page for instructions on how to do that, then come back to conintue this tutorial.

That being said, here is a screen shot of what my finder looks like with the GUI:
![screen shot 2017-02-16 at 12 59 33 pm](https://cloud.githubusercontent.com/assets/11437469/23033897/ce8656c6-f447-11e6-8cd4-bf95d8ea1470.png)

You can see the executable app placed right in the applications folder, this is new to Sierra.

Also please do not use the Dongle with Mac OS, just use the built in BLE.

**Comment by HMBTECP** [comment]
@aj-ptw 
Thank you very much for your detailed answer 
but i already did all these steps.
and i already read about the getting started in Ganglion webpage

**Comment by aj-ptw** [comment]
Is this issue still persisting?

**Comment by ds1** [comment]
This problem still persists for me. I've tried both as a standalone application and running from the .pde file.

-Updated FTDI drivers
-Ganglion Hub is running

I'm running Mac Sierra 10.12.3 and have followed the instructions here: http://docs.openbci.com/OpenBCI%20Software/00-OpenBCISoftware

I've tried opening Bluetooth Preferences and no devices appear.
They don't appear when I refresh the list in the Open BCI GUI either in the LIVE (from Ganglion) option.

**Comment by aj-ptw** [comment]
Are you using a BLE dongle? Mac does not use dongle

**Comment by armengol** [comment]
I'm running Mac Sierra 10.12.5. I just bought a Ganglion board and I am facing the same problem. My board does not appear in the list of BLE devices in OpenBCI_GUI. I followed all the steps in "Ganglion Getting Started Guide" but problem is persisting. I can find the device using a BLE device scanner app, so the problem does not come from the board itself.
Any suggestions?

Thank you.

**Comment by WillWillyto** [comment]
Yup, same problem here. Running macOS Sierra Version 10.12.5 and neither the GUI nor the built in Bluetooth system are detecting my Ganglion board. Moved the app to the Applications folder as mentioned above and gave the administrator rights to the app but still nothing happens.
Suggestions are very welcome.

Thank you.

**Comment by aj-ptw** [comment]
Can you please try running an earlier version such as v2.2.0

http://openbci.com/index.php/software

**Comment by WillWillyto** [comment]
worked. love you!

**Comment by aj-ptw** [comment]
Weird! Looking into the problem.

**Comment by armengol** [comment]
It worked thanks!!

**Comment by aj-ptw** [comment]
Did you recently update? I know my computer has been asking me for a while

**Comment by VessoVit** [comment]
10.13 same issue

**Comment by aj-ptw** [comment]
@VessoVit please open a new issue with the GUI version you're running and os?

**Comment by rschaef1** [comment]
I am having the same issue with OS Mojave 10.14, and unfortunately neither version 3.2 or 2.2 has worked for me. When I updated my OS the ganglion board just stopped showing up on bluetooth
