### ISSUE TITLE
Networking Bugs

### ISSUE THREAD

**Issue by conorrussomanno** [OpenBCI/OpenBCI_GUI#134]
- [ ] when you hide the networking widget, or go back to the Control Panel, the widget's CP5 options are still visible
- [ ] when typing in the Textfields, the characters are sent to the board, For example, if you type an 's' while typing in a Textfield, your board will stop streaming. I wonder if there is a way to "block" messages to the board while Textfields are active?
- [ ] widen dropdown menus and text fields so "TimeSeries" doesn't spill over
- [ ] if you have an OSC stream open and then you select LSL from the protocol dropdown, the application freezes

**Comment by daniellasry** [comment]
Closing as these are fixed/no longer applicable.
