### ISSUE TITLE
Could not connect open bci with open vibe acquisition server

### ISSUE THREAD

**Issue by AshmitDadhich9696** [OpenBCI/OpenBCI_GUI#135]
Hello

We are facing problem in interfacing Openvibe with OPenBCI V3-32 Board. Openvibe with Generic oscilattor is working good and we getting signal in OPenBCI GUI from our open bci board. We also did driver settings and changes in Preferences as per the instructions provide on website of open bci.But unable to cope up with problem.We also followed instructions given in documentation.
currently using open vibe 1.3.0 on windows 7 OS

Error : No response from the driver in 1000ms
here by i am providing the screen shot of the terminal please help me out
![error](https://cloud.githubusercontent.com/assets/25990059/23278181/a1595dfc-fa36-11e6-93d9-0b0d9030a8e3.PNG)

**Comment by aj-ptw** [comment]
Hi are you able to use the processing GUI?

**Comment by aj-ptw** [comment]
Closing because you are saying it's working in this GUI. Could you route the question over to the OpenVibe team? We don't use the program in house. Sorry this would frustrate me too!

Thanks!
