### ISSUE TITLE
Duplication Library Problem

### ISSUE THREAD

**Issue by CQUPTFC** [OpenBCI/OpenBCI_GUI#141]
Hi, when I run the OpenBCI_GUI, there is an error like this:
![error](https://cloud.githubusercontent.com/assets/26280983/23786774/cd4fb11c-05a9-11e7-9d76-5d9203f7183a.png)
When I remove one of those two versions,the procedure will occur an error.
![error](https://cloud.githubusercontent.com/assets/26280983/23786831/1ba7e780-05aa-11e7-8564-2267b741368f.png)
My processing version is 2.21.

**Comment by aj-ptw** [comment]
Use processing 3
