### ISSUE TITLE
OpenGL error at bot beginDraw() and time out error

### ISSUE THREAD

**Issue by MirzaUbaidullahBaig** [OpenBCI/OpenBCI_GUI#146]
![screenshot from 2017-03-22 10-28-46](https://cloud.githubusercontent.com/assets/26623920/24296000/11edf232-10bf-11e7-99b3-50ccac6d1905.png)

I am running this code in raspberry pi 2 (also tried in 3) with this error only black window appears.

I also tried and older code from [https://github.com/OpenBCI/OpenBCI_Processing](url)
it runs but don't show any signals aslo with same errors. 
![screenshot from 2017-03-22 10-40-09](https://cloud.githubusercontent.com/assets/26623920/24296323/81cca9a8-10c0-11e7-90eb-e7648d911340.png)
![screenshot from 2017-03-22 10-40-37](https://cloud.githubusercontent.com/assets/26623920/24296324/81d0ab66-10c0-11e7-9489-8df5ef071ecc.png)

**Comment by aj-ptw** [comment]
Are you able to run any processing file?

**Comment by MirzaUbaidullahBaig** [comment]
I just ran some basic example codes and one that i used with arduino in processing to be sure. there is no problem in running. 
![image](https://cloud.githubusercontent.com/assets/26623920/24298950/668fbf78-10c9-11e7-9339-cf9769c4c4a5.png)

**Comment by aj-ptw** [comment]
do the examples use OpenGL?

**Comment by MirzaUbaidullahBaig** [comment]
i don't know if you know any example that use openGL, give me.

**Comment by aj-ptw** [comment]
The processing GUI uses OpenGL, that's the only example I can provide. I'm not familiar with what it takes to run OpenGL on raspberry pi

**Comment by MirzaUbaidullahBaig** [comment]
I'll google some examples. w8

**Comment by MirzaUbaidullahBaig** [comment]
There are 3 graphic drivers in raspberry pi one is default non-gl driver, others are experimental GL drivers. I enabled one of those drivers.
![image](https://cloud.githubusercontent.com/assets/26623920/24310550/2b00ca14-10f2-11e7-8901-d1b0d38145ac.png)
still got the same error.
Please help me.

**Comment by aj-ptw** [comment]
Maybe this application is too much for raspberry pi, not sure there is anything we can do to help you.
