### ISSUE TITLE
OpenBCI GUI not saving BDF+ files

### ISSUE THREAD

**Issue by katie356** [OpenBCI/OpenBCI_GUI#147]
My OpenBCI GUI is saving txt readings fine, but when I switch to BDF+ format, nothing gets saved. Note, this is happening with my Ganglion, but I don't have a Cyton so I can't say if this is board specific.

**Comment by aj-ptw** [comment]
possible connection with #121

**Comment by aj-ptw** [comment]
@katie365 are you pressing `STOP SYSTEM` when you finish your session? That triggers the save when you're close the connection! Sorry for taking two months to fix this. I'm going to get BDF writer working.

**Comment by aj-ptw** [comment]
closing for now
