### ISSUE TITLE
LSL connection doesn't send stream correctly

### ISSUE THREAD

**Issue by rodrigohubner** [OpenBCI/OpenBCI_GUI#148]
The follow error ocurred when I execute the receive code:
```
$ java -Djna.nosys=true -cp "jna-4.2.2.jar:." examples.ReceiveData
Resolving an EEG stream...
Note: The stream named '(invalid: bad lexical cast: source type value could not be interpreted as target)' could not be recovered automatically if its provider crashed because it does not specify a unique data source ID.
Error while receiving the stream info (Invalid argument); retrying...
edu.ucsd.sccn.LSL$LostException: The stream has been lost.
	at edu.ucsd.sccn.LSL.check_error(LSL.java:900)
	at edu.ucsd.sccn.LSL$StreamInlet.info(LSL.java:568)
	at edu.ucsd.sccn.LSL$StreamInlet.info(LSL.java:569)
	at examples.ReceiveData.main(ReceiveData.java:14)
```
I have the problem using "send" in java and "receive" in everything else language.

**Comment by aj-ptw** [comment]
Post code that you are using, the parser is not able to get the string name. So there is something wrong with the way you are using stings. Or post a screen shot. Are you using " in the call?

**Comment by rodrigohubner** [comment]
I connected the send data with GUI.
The code in python is the basic example on https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/examples/ReceiveData.py
So, when I start the send data with LSL connection on GUI and run the script shows this error:
```
$ python ReceiveData.py 
looking for an EEG stream...
Note: The stream named '(invalid: bad lexical cast: source type value could not be interpreted as target)' could not be recovered automatically if its provider crashed because it does not specify a unique data source ID.
Traceback (most recent call last):
  File "ReceiveData.py", line 10, in <module>
    inlet = StreamInlet(streams[0])
  File "/home/rhubner/.anaconda2/lib/python2.7/site-packages/pylsl/pylsl.py", line 641, in __init__
    self.sample = self.sample_type()
TypeError: 'list' object is not callable
```

**Comment by rodrigohubner** [comment]
@aj-ptw Is there some way to create a script in Python to send LSL stream from OpenBCI GUI?

Because honestly, the biggest problem for me is with Java. I just wanted something using OpenBCI to send LSL data showing the signal in time...

**Comment by aj-ptw** [comment]
@rodrigohubner yes this example was written by @gabrielibagon https://github.com/OpenBCI/OpenBCI_NodeJS/tree/master/examples/labstreaminglayer

It's a very stable driver.

**Comment by rodrigohubner** [comment]
But it would be better to see the EEG signal in time on a graph! OpenBCI GUI is great but not works the LSL send for me...

**Comment by aj-ptw** [comment]
totally get what you are saying! it's a good visual!

**Comment by rodrigohubner** [comment]
I didn't know how to do it using OpenBCI_NodeJS with LSL. Can you explain the steps to me by e-mail, please? (off topic to this issue). rhubner@gmail.com

**Comment by aj-ptw** [comment]
Sorry! I didn't write this part so all i can do is point you to the instructions found here https://github.com/OpenBCI/OpenBCI_NodeJS/blob/master/examples/labstreaminglayer/readme.md
If the instructions are unclear, please open an issue in that repo. Thanks so much!

**Comment by aj-ptw** [comment]
@rodrigohubner you should check out the development branch https://github.com/OpenBCI/OpenBCI_GUI/tree/development look like gabe added LSL support on the last commit? not sure @conorrussomanno may know better

**Comment by aj-ptw** [comment]
fixed on master AFAIK, please reopen if issues persist
