### ISSUE TITLE
Playback for ganglion record's looks noisy

### ISSUE THREAD

**Issue by likeleto** [OpenBCI/OpenBCI_GUI#149]
Started GUI in playback mode for the record from ganglion. Discovered that time series graph looked very noisy compared to live stream.
Here the comparison
![playbackvslive](https://cloud.githubusercontent.com/assets/10817195/25286652/2ed08324-26c7-11e7-9721-1bc892e25c34.png)

**Comment by aj-ptw** [comment]
Hmm this is interesting. Did you try selecting four channels instead of eight?

**Comment by likeleto** [comment]
@aj-ptw  that's the thing, 4 channels was chosen, but in playback, it looks like in the left picture. So I might guess that GUI in playback mode doesn't know anything about ganglion and think that it is 8ch cynton.

**Comment by aj-ptw** [comment]
what version of the GUI are you using?

**Comment by likeleto** [comment]
@aj-ptw mac, 2.1.2 (from site and through processing, same behavior)
attach example of record from my ganglion
[OpenBCI-RAW-2017-04-15_01-14-57.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/1012552/OpenBCI-RAW-2017-04-15_01-14-57.txt)

**Comment by aj-ptw** [comment]
@likeleto just tried running and the data looks pretty good http://g.recordit.co/CzjHkjbROb.gif

I used a patched version of the GUI that allows for four channels in playback see pr #157 which was started because of #151 

If that's EEG then it's pretty good, your channel 1 looks very noisy, try a different electrode?

**Comment by likeleto** [comment]
@aj-ptw Thank you for patch, I've just tested updated version. There're is still the difference. Why does playback graph not show the same picture as the live graph?
**LIVE**
<img width="1338" alt="screen shot 2017-05-31 at 19 49 06" src="https://cloud.githubusercontent.com/assets/10817195/26643579/7693d138-463a-11e7-918d-3c608e64b562.png">

**PLAYBACK**
<img width="1439" alt="screen shot 2017-05-31 at 19 49 23" src="https://cloud.githubusercontent.com/assets/10817195/26643575/736b2484-463a-11e7-9d32-a6227112c0cd.png">
Thanks again for your help.

**Comment by aj-ptw** [comment]
is it possible that the filters are not being set? please see if the notch and band pass are on!

**Comment by likeleto** [comment]
Notch and BP were set, settings on pictures the same...

**Comment by aj-ptw** [comment]
Have you reached out to @biomurph ?

**Comment by daniellasry** [comment]
Closed by #159
