### ISSUE TITLE
Issue Running GUI from source

### ISSUE THREAD

**Issue by lYlantis** [OpenBCI/OpenBCI_GUI#150]
When I download the repo and try to run from source, I am getting this error message:

![issue](https://cloud.githubusercontent.com/assets/11239651/25540924/c7e6415e-2c1a-11e7-96e3-87ab522e79ed.PNG)

Even though in libraries is GifAnimation and UDP which I assumed was the other library I needed.

![issue2](https://cloud.githubusercontent.com/assets/11239651/25540949/ea2fa304-2c1a-11e7-9698-58ce2f4eacc0.PNG)

I tried dragging and dropping the folder into the sketch folder as mentioned in an earlier issue. I am on Windows 10.

**Comment by aj-ptw** [comment]
Hi is this issue still persisting?

Are your preferences set correctly inside processing? Prefresences -> Sketchbook location -> Folder where all these libs are placed.

**Comment by aj-ptw** [comment]
Hi please let us know if this issue is still outstanding! Closing for now.

Thanks!
