### ISSUE TITLE
SD Card File Converter

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#164]
Needs option to convert SD file from HEX to BDF or ODF.
Find a stand alone SD file converter here
https://github.com/biomurph/OBCI_HEX_SD_File_Converter

**Comment by biomurph** [comment]
Already converts to file type that is readable by GUI for playback. Would it be easier to add a way to have the GUI generate the BDF file on playback?

**Comment by retiutut** [comment]
@daniellasry This issue can be closed.
