### ISSUE TITLE
Run it, But it show: please fix the size() line to continue.

### ISSUE THREAD

**Issue by neotim** [OpenBCI/OpenBCI_GUI#166]
![screen shot 2017-06-13 at 5 30 52 pm](https://user-images.githubusercontent.com/14356809/27111164-280ffbd0-5063-11e7-8f0d-9fd5113cb2d6.png)
![screen shot 2017-06-13 at 5 31 05 pm](https://user-images.githubusercontent.com/14356809/27111163-280e8142-5063-11e7-8091-23a4fa9d4c92.png)

Run it, But it show: please fix the size() line to continue.

**Comment by aj-ptw** [comment]
@neotim 

Thanks for using and supporting the OpenBCI GUI!

_This issue seems like a missing dependency_

Did you configure the libraries correctly? (Show a screen shot of your preferences page in processing, I want to see your `Sketchbook folder:`. Then take a screen shot of that finder window where the `Sketchbook folder` is pointing to)

What version of Mac OS are you running?
What version of the GUI are you trying to run? (when did you download it?)

Thanks!

**Comment by neotim** [comment]
Thank you for your reply, these are screen shots:
![screen shot 2017-06-14 at 10 27 32 am](https://user-images.githubusercontent.com/14356809/27145976-8f713bf2-50ec-11e7-884a-c7233cb941f8.png)
![screen shot 2017-06-14 at 10 28 25 am](https://user-images.githubusercontent.com/14356809/27145975-8f6f89c4-50ec-11e7-8bb5-7a9a88389fcd.png)
![screen shot 2017-06-14 at 10 28 49 am](https://user-images.githubusercontent.com/14356809/27145974-8f6d42e0-50ec-11e7-9dce-7fba3762fc2b.png)


// GUI for controlling the ADS1299-based OpenBCI
// Created: Chip Audette, Oct 2013 - May 2014
// Modified: Conor Russomanno & Joel Murphy, August 2014 - Dec 2014

**Comment by aj-ptw** [comment]
Can you please show me a screen shot of where `/Users/devupload/Documents/Processing`

Mine looks like this:
![screen shot 2017-06-14 at 2 58 51 pm](https://user-images.githubusercontent.com/11437469/27149608-28b448ca-5112-11e7-9f3f-887560f2303a.png)

**Comment by neotim** [comment]
ok, this is the screen shot of /Users/devupload/Documents/Processing:
![screen shot 2017-06-14 at 3 20 58 pm](https://user-images.githubusercontent.com/14356809/27157168-34e230d2-5115-11e7-812d-ece64cf5c651.png)

**Comment by aj-ptw** [comment]
Can you please download processing 3.3 **NOT** 3.3.4 and let me know if that helps.

**Comment by neotim** [comment]
now is processing 3.3, same error:

![screen shot 2017-06-14 at 3 35 49 pm](https://user-images.githubusercontent.com/14356809/27158148-44d81394-511a-11e7-83c1-a7f98ec0e05c.png)

**Comment by aj-ptw** [comment]
So it looks like you have the new version of the GUI inside the old version the GUI. You should clone the gui into a new directory. The size error is coming from the old gui code...

**Comment by neotim** [comment]
yes, this old gui is from https://github.com/viguix/OpenBCI_GUI_Helicopter_Throttle
need to control copter.

**Comment by aj-ptw** [comment]
I think that was done using processing 2.x not 3.

Closing this issue

**Comment by neotim** [comment]
now is processing 2.2.1: 
![Uploading Screen Shot 2017-06-14 at 5.34.06 PM.png…]()

**Comment by aj-ptw** [comment]
Glad to see you opened on @biomurph repo. He's good and will help. Good luck!

**Comment by ronnyandre** [comment]
Same error with Processing 3.5.2

**Comment by Redha-Ferradji** [comment]
you just need to replace size () with surface.setSize () and for more information
https://github.com/processing/processing/wiki/Changes-in-3.0
