### ISSUE TITLE
how to solve OpenBCI_GUI.HexBug.Command is undefined

### ISSUE THREAD

**Issue by neotim** [OpenBCI/OpenBCI_GUI#167]
HexBug(Serial serialPort) {
int ID = 0;// display comands
command_forward = new Command(serialPort,"O","Swim!",ID++);
command_right = new Command(serialPort,"|","Right",ID++);
command_left = new Command(serialPort,"{","Left",ID++);
command_climb = new Command(serialPort,"}","Climb",ID++);
command_dive = new Command(serialPort,"P","Dive",ID++);
![screen shot 2017-06-14 at 5 34 06 pm](https://user-images.githubusercontent.com/14356809/27248818-c2004e82-52bd-11e7-993f-971a4255a2a0.png)

**Comment by aj-ptw** [comment]
Hi this code is not in this repository, please open the issue on the repo of which you got it from. Thanks! Closing issue for now.
