### ISSUE TITLE
OpenBCI not listing BLE devices

### ISSUE THREAD

**Issue by gilesforrest** [OpenBCI/OpenBCI_GUI#178]
My Ganglion is visible via BLE on other software but doesn't display in the Open BCI GUI.

E.g. using Noble (node.js) peripheral explorer:

peripheral with ID ea0b6ab6750c found
  Local Name        = Ganglion-40ed
  Service Data      =
  Service UUIDs     =

services and characteristics:
1800 (Generic Access)
  2a00 (Device Name)
    properties  read, write
    value       53696d626c6565 | 'Simblee'
  2a01 (Appearance)
    properties  read
    value       0000 | '  '
  2a04 (Peripheral Preferred Connection Parameters)
    properties  read
    value       1000180000006400 | '    d '
1801 (Generic Attribute)
  2a05 (Service Changed)
    properties  indicate
180a (Device Information)
  2a29 (Manufacturer Name String)
    properties  read
    value       6f70656e6263692e636f6d | 'openbci.com'
  2a24 (Model Number String)
    properties  read
    value       47616e676c696f6e | 'Ganglion'
  2a27 (Hardware Revision String)
    properties  read
    value       312e302e30 | '1.0.0'
  2a26 (Firmware Revision String)
    properties  read
    value       312e312e30 | '1.1.0'
  2a28 (Software Revision String)
    properties  read
    value       302e312e30 | '0.1.0'
fe84
  2d30c082f39f4ce6923f3484ea480596
    properties  read, notify
    value        | ''
  2d30c083f39f4ce6923f3484ea480596
    properties  writeWithoutResponse, write
  2d30c084f39f4ce6923f3484ea480596
    properties  writeWithoutResponse, write
000015301212efde1523785feabcd123
  000015321212efde1523785feabcd123
    properties  writeWithoutResponse
  000015311212efde1523785feabcd123
    properties  write, notify
  000015341212efde1523785feabcd123
    properties  read
    value       0100 | ' '

**Comment by aj-ptw** [comment]
Are you on Mac? Win? Linux? 

Using ble dongle?

**Comment by aj-ptw** [comment]
What version of the GUI are you using?

**Comment by gilesforrest** [comment]
Hi,
Using Windows 10 with a BLE dongle (installed CSR Harmony then driver replaced using Zadig)
Version of OpenBCI GUI is the newest just downloaded 2.2.

Giles

**Comment by gilesforrest** [comment]
Yes it is.

**Comment by gilesforrest** [comment]
Hi...any thoughts on how to help?

**Comment by gilesforrest** [comment]
This is resolved - I didn't have the openBCI programme within my program files folder. Also I set it to Run as administrator.

**Comment by aj-ptw** [comment]
So it always runs as administrator automatically? I did not know you could do that.

**Comment by gilesforrest** [comment]
Yes, right click on the executable -> properties -> compatibility -> tick "Run this program as an administrator"

**Comment by aj-ptw** [comment]
Cool. Thanks to you I added [this to the docs](http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-using-the-openbci-gui-as-a-standalone-application-install-the-application):

### Install the Application

Next, you must save the application somewhere, the same way you would any other application or executable on your machine. 

#### On Mac

Place the OpenBCI_GUI in your /Applications folder. If the GUI fails to boot the first time, reboot it, a second popup will come up that asks about running the GanglionHub for the first time, please press "OK".

#### On Windows

Please place the GUI in your Program Files directory such that the structure looks like:
"\Program Files\OpenBCI_GUI\OpenBCI_GUI.exe"

Lastly, right click on the executable -> properties -> compatibility -> tick "Run this program as an administrator".
