### ISSUE TITLE
Dongle instructions in Software menu need clarification

### ISSUE THREAD

**Issue by ali1632** [OpenBCI/OpenBCI_GUI#182]
In the Getting Started documentation for OpenBCI_GUI, there is an instruction which says: 

"The signal will not work if the Dongle is connected on a Mac."
http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-using-the-openbci-gui-as-a-standalone-application-connect-the-usb-dongle-only-if-you-use-windows-or-linux

(Please note this is not in the tutorials, but under the software menu.)

I'm now understanding that this is relevant only to the Ganglion board. I guess the documentation needs a tweak? 

Original question in the forum: http://openbci.com/forum/index.php?p=/discussion/1203/does-the-rfduino-dongle-work-with-osx#latest

Thanks!
Ali

**Comment by aj-ptw** [comment]
Thanks!

I fixed the docs! It's only through people like you that we can improve!
