### ISSUE TITLE
Focus Widget colors

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#192]
The colors in the focus widget make the data and bars very hard to read

**Comment by aj-ptw** [comment]
@sunwangshu Could you please select a different color scheme for the focus widget background color and/or text font color? Joel and I were in love with the new widget but were had a tough time reading the text labels and such. Awesome work!

**Comment by aj-ptw** [comment]
Also the popup help window you made is amazing!!!!

**Comment by sunwangshu** [comment]
Hi I just found it here recently...
Got a bunch which do you guys like?
![cyan](https://user-images.githubusercontent.com/14167797/32309794-4752af90-bf4b-11e7-9bbc-38da2183c0f6.jpeg)
![green](https://user-images.githubusercontent.com/14167797/32309797-4ca71bd4-bf4b-11e7-9cf9-0d9eabe0aaaa.jpeg)
![orange](https://user-images.githubusercontent.com/14167797/32309799-4f460a8a-bf4b-11e7-9039-177a3c6bda11.jpeg)

**Comment by sunwangshu** [comment]
Hello I just pushed the update please check it #289

**Comment by aj-ptw** [comment]
@sunwangshu awesome!! Thanks so much! Will include in the next release!

**Comment by aj-ptw** [comment]
This was patched with [v3.2.0 release](https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.2.0)! Thanks so much @sunwangshu
