### ISSUE TITLE
No Streaming Data from Ganglion

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#196]
Flashed a Ganglion with the DefaultGanglion firmware from the development branch of the Ganglion_Library repo. I checked with an older version of the GUI, and same issue.
Also checked with a Ganglion flashed with the current master, and it does work with the older GUI.
Here's the breakdown:

DefaultGanglion from Master Branch of Ganglion Library
Works on older GUI. Streaming and Accel
No streaming on this development branch, accel works

DefaultGanglion from Development Branch of Ganglion Library
Works on older GUI. Streaming and Accel
No streaming on this development branch, accel works

**Comment by aj-ptw** [comment]
Are you saying it didn't work for you?

**Comment by biomurph** [comment]
yup. looks like the problem is with the development GUI or hub. The Ganglion firmware that includes the wifi library works on the older GUI that I have, but not the newer one...
