### ISSUE TITLE
Ganglion Accelerometer not working

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#208]
I don't see the Ganglion Accel data coming through on the GUI in Wifi

**Comment by aj-ptw** [comment]
I need the correct scale factors for the accelerometer, the data is coming in but the scale is wrong.

**Comment by aj-ptw** [comment]
@biomurph Do you think you could dig up the new scale factors for the Ganglion Accel over wifi?
 Would really really help!
