### ISSUE TITLE
Ganglion Impedance Not working

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#209]
Java error when sending command to check Ganglion impedance.
Kills the board. Have to reboot the Ganglion to get it back in shape.

**Comment by aj-ptw** [comment]
This will require 
- [ ] Ganglion firmware update to support impedance through wifi
- [ ] Will need a new packet number so the data can be parsed over TCP
- [ ] Edit `OpenBCI_NodeJS_Utilities` to support new packet type
- [ ] Add in `OpenBCI_NodeJS_Wifi` function for impedance for ganglion
- [ ] Update `OpenBCI_Ganglion_Electron` for new wifi feature

**Comment by aj-ptw** [comment]
woo this was a bigly issue
