### ISSUE TITLE
GUI can't pass thru commands to tell Ganglion to prep and write to SD card

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#212]
While the SD card write is a bit of a no-go right now due to noise, we should be able to use the commands in the GUI anyway, at least in a development branch, so that we can debug and maybe solve the Ganglion SD writing more easily.

**Comment by aj-ptw** [comment]
@biomurph can you test this with the latest `development` branch code? These commands should be sent to the Ganglion.

**Comment by aj-ptw** [comment]
Fixed in [v3.1.0](https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.1.0)
