### ISSUE TITLE
Fails to connect w/ WiFi and gives incorrect helpWidget log.

### ISSUE THREAD

**Issue by conorrussomanno** [OpenBCI/OpenBCI_GUI#229]
Occasionally, when attempting to connect w/ WiFi+Cyton, the connection fails and prints "Dang! Lost Connection To Ganglion..." to the helpWidget at the bottom of the GUI. See screenshot:

![screen shot 2017-09-03 at 8 52 18 pm](https://user-images.githubusercontent.com/412051/30011483-75632dca-90ec-11e7-9844-3d4955ed2dab.png)

**Comment by aj-ptw** [comment]
i think i fixed this
