### ISSUE TITLE
3.0.0-rc3 Pulse Sensor Widget not graphing

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#245]
Pulse Sensor widget doesn't graph the data. It does appear that the analog read command gets passed to the Cyton and that the Cyton is doing analog read on the pins, but the graphing is not happening. Tried to change the aux value from [0] to [1] and still not graphing.

**Comment by aj-ptw** [comment]
Hi joel, this needs follow up with you on new GUI
