### ISSUE TITLE
Cyton Wifi FFT max always at 100Hz

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#246]
Running Wifi and Cyton. If I choose 250Hz sample rate or 1000Hz sample rate in the setup, I see the FFT only graphs up to 100Hz...

**Comment by aj-ptw** [comment]
thank you!! I see the same problem too!!

**Comment by aj-ptw** [comment]
any thoughts about this mr @biomurph?

**Comment by biomurph** [comment]
Well, there was an issue that I brought up about not being able to select 100Hz max or 500Hz max depending on what sample rate you use (Nyquist)... So it seems like when that got fixed it might have broken this somehow?

**Comment by aj-ptw** [comment]
ah okay that's a good place to look

**Comment by sunwangshu** [comment]
Can you run the board with 1000Hz, then print out the value of getSampleRateSafe() and fs_Hz in the draw() loop of OpenBCI_GUI.pde?

**Comment by aj-ptw** [comment]
It says 1000

**Comment by sunwangshu** [comment]
OK I'll check it out later about buffer stuff

**Comment by aj-ptw** [comment]
let's do a Skype!!

**Comment by sunwangshu** [comment]
Fixed

**Comment by aj-ptw** [comment]
fixed in v3.2.0
