### ISSUE TITLE
Moving from Pulse Sensor messes with Accelerometer

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#249]
If you turn the analog read on in the Pulse Sensor widget, then move to the accelerometer widget, the accelerometer data is not there.

**Comment by aj-ptw** [comment]
Would I display a message that the board is in analog mode?

**Comment by aj-ptw** [comment]
This should be fixed in the [latest v3.2.0 stable release](https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.2.0). Please comment here if that's not the case!
