### ISSUE TITLE
Bottom bar says "Wifi refreshing" when BLE is not started

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI#253]
> The bottom tool bar displays a message "Wifi devices refreshing". Is this a bug which actually searches for devices through Wifi rather than BLE?

**Comment by iblues93** [comment]
I think this one is solved by running both Hub and GUI as administrator. The problem is gone along with the referenced closed issue.

**Comment by aj-ptw** [comment]
Unfortunately an error message should be displayed if the hub is running but the BLE is not working that says follow tutorial with a link instead of saying Wifi refreshing. :) it's a bug, a minor one, but still a bug.

**Comment by iblues93** [comment]
Ahh I see. Thanks so much for the active support you and your team have been providing.

**Comment by aj-ptw** [comment]
Fixed in [v3.1.0](https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.1.0)
