### ISSUE TITLE
OpenBCI GUI hangs when LSL starts streaming

### ISSUE THREAD

**Issue by iblues93** [OpenBCI/OpenBCI_GUI#254]
Hi guys, I have tried to stream data using the LSL on the GUI, however, the GUI hangs after I started the stream. Is there a remedy to get this to work?

-Windows 7
-OpenBCI GUI V3.0 (both hub and GUI are running with admin privilleges.
-Ganglion

**Comment by iblues93** [comment]
*Update*

I have installed processing to run the GUI. Apparently, there is a problem with the LSL function to stream. Here is a screenshot of the error message. I will try  to see what I can do from here.
![lsl error](https://user-images.githubusercontent.com/19729869/30167559-5f393992-9419-11e7-85c8-9d3884c9efdb.png)

**Comment by aj-ptw** [comment]
Awesome! I will patch this later today and publish an update! Thanks!

**Comment by iblues93** [comment]
Thank you so much! Looking forward to it :)

**Comment by aj-ptw** [comment]
Please pull master for the bug patch

**Comment by iblues93** [comment]
Thank you so much :)

**Comment by aj-ptw** [comment]
@iblues93 can you please test the new release to make sure this bug is really fixed?

https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.0.1

**Comment by iblues93** [comment]
sorry for the late response, been busy the past few days. I will test it later when my lesson ends

**Comment by iblues93** [comment]
Good day aj-ptw! I have tried it through processing and it works now. However, if it is runned as a standalone, it doesn't.
