### ISSUE TITLE
Inputs frequently showing RAILED, high input amplitude

### ISSUE THREAD

**Issue by brylie** [OpenBCI/OpenBCI_GUI#257]
I have an OpenBCI Ganglion board, and have closely followed the Getting Started guide (even the electrode placement/colors). The impedance values for all four channels are < 30 kΩ. However, when running the data stream, there seems to be abnormally high amplitude, with the word RAILED showing up frequently in all four channels:

![peek 2017-10-05 11-52](https://user-images.githubusercontent.com/17307/31218894-586281e4-a9c4-11e7-81d8-bd6f3dfd4267.gif)

Is this a normal looking data stream? What can I do to improve the data stream, e.g. reducing the amplitude?

**Comment by aj-ptw** [comment]
That is very strange looking data indeed!

Can you tell us what your OS is?

**Comment by aj-ptw** [comment]
Also @biomurph thoughts?

**Comment by brylie** [comment]
I am running Ubuntu 17.04 (Kubuntu).

**Comment by aj-ptw** [comment]
Hmm this looks like dropped packets, could you share one of your saved data files?

**Comment by brylie** [comment]
Here is some of the raw data saved by OpenBCI GUI:

[OpenBCI-RAW-2017-10-06_09-48-55.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/1407748/OpenBCI-RAW-2017-10-06_09-48-55.txt)

**Comment by Obad94** [comment]
I'm also having the same issue . Have you got any luck to overcome this issue ?

**Comment by Obad94** [comment]
@andrewjaykeller ?

**Comment by daniellasry** [comment]
I believe this ganglion impedance issue was fixed by @retiutut
