### ISSUE TITLE
ADD: Report firmware version of Cyton and Ganglion

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_GUI#259]
There should be a way to easily get the Cyton/Ganglion firmware version number from the GUI

**Comment by aj-ptw** [comment]
To make this happen, one would:

- [ ] Add function in OpenBCI_NodeJS_Ganglion to get version number of Ganglion
- [ ] Add function in OpenBCIHub to send back version number of Cyton
- [ ] Add GUI component for getting version number.

**Comment by xueting123456** [comment]
Hi, hello. I saw your information on GitHub. Do you have the code to calculate the peak time difference through 2 pulse sensors?

**Comment by aj-ptw** [comment]
Please open another issue for this

**Comment by aj-ptw** [comment]
This issue is solved in the latest gui v3.3.0
