### ISSUE TITLE
No accelerometer data while using Cyton and Daisy combo with wifi shield

### ISSUE THREAD

**Issue by msmadan** [OpenBCI/OpenBCI_GUI#265]
I am not getting any accelerometer data while using Cyton and Daisy combo with wifi shield
-Raja

**Comment by aj-ptw** [comment]
Hi i've fixed this with a new hub, will be posting a new binary for this soon.

**Comment by msmadan** [comment]
Thanks AJ
-Raja

**Comment by msmadan** [comment]
Hi can please let me the ETA on the new binary
Thanks
Raja

**Comment by aj-ptw** [comment]
@msmadan please find here:
https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.1.0-beta1

What operating system?

**Comment by msmadan** [comment]
Windows 10

**Comment by aj-ptw** [comment]
Ah okay I need to run home to build for windows. Binary coming soon!

**Comment by aj-ptw** [comment]
@msmadan please download binary from:
https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.1.0-beta2

Thanks

AJ

**Comment by msmadan** [comment]
I will test it today and let you know how it works.
Thanks for the help
raja

**Comment by aj-ptw** [comment]
Great

**Comment by msmadan** [comment]
I tested the system today.I am getting the accelerometer data now.I am getting the accelerometer data at 25Hz , Is there any way this can be increased

**Comment by aj-ptw** [comment]
@msmadan this is possible but you’re the first person to ask AFAIK.

I would ask that you read the data sheet for the accel on the Cyton and add the code to OpenBCI_32bit_Library for others to use!

If you do not want to code this feature, please open an issue on OpenBCI_32bit_Library with as much details as you can about the feature. We will, or someone will, add the feature in.

**Comment by msmadan** [comment]
I will try to code it and see if I can get it to work . If I get it to work I will upload it.
Thanks
Raja

**Comment by aj-ptw** [comment]
Awesome!

**Comment by aj-ptw** [comment]
This was fixed in [v3.1.0](https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v3.1.0)
