### ISSUE TITLE
Data stream freezes when saving in the BDF+ file type

### ISSUE THREAD

**Issue by GeneralFox2** [OpenBCI/OpenBCI_GUI#266]
Greetings,

I want to use the BDF+ file type so I do not have to convert the data in EDFbrowser to BDF for import into EEGLAB. 

I am able to see a continuous data stream when the selected data type is OpenBCI, however when I choose "BDF+" the data stream will stop in the interface after some time.  When this happens, the interface continues to work - I can change anything on the GUI I want (Vertical Scale, the information presented in each frame, etc. etc.. The file size is relative to the amount of time before the data stream stops in the GUI.  I choose to stop the data stream, then I can STOP SYSTEM.  I then return to the GUI, where I can try again.  If I choose OpenBCI file type, then the system works without issue.

I have shut down my anti-virus, and etc.. (BitDefender).  Any suggestions?

Thanks,
Don

**Comment by aj-ptw** [comment]
Could you post a screen shot of what happens when it stops? The file is written at the end of the session so be sure to hit stop session and give it a couple seconds.

AJ Keller
Push The World

**Comment by aj-ptw** [comment]
Sound like you are saying the GUI freezes while recording?

The gui may hang at the end because it has to rewrite the whole file. Give it a bit!

**Comment by aj-ptw** [comment]
Don. Ouch that is annoying. Will record some long sessions tomorrow and see if we can duplicate. Great write up thanks.

**Comment by aj-ptw** [comment]
How long do you stream for? I'm 3 minutes in and still streaming.

**Comment by aj-ptw** [comment]
sorry didn't mean to close!

**Comment by aj-ptw** [comment]
I'm not able to duplicate. Any suggestions?

**Comment by aj-ptw** [comment]
Please take a screen shot so i can see how many seconds have passed and such.

**Comment by GeneralFox2** [comment]
Hi,  

I'm sorry you cannot duplicate this.  I'm uncertain as to which direction to take now as I am unfamiliar with the coding behind.

I have attached the images by "selecting them" below. 

![freeze 1](https://user-images.githubusercontent.com/32853996/31921059-12c23046-b83b-11e7-9ba7-d217a5c42f67.jpg)
![freeze 2](https://user-images.githubusercontent.com/32853996/31921062-19c727ca-b83b-11e7-8b6d-f8cf898e93d9.jpg)
![freeze 3](https://user-images.githubusercontent.com/32853996/31921191-fa618e1a-b83b-11e7-829a-845d4cc69d06.jpg)

[BDF File.zip](https://github.com/OpenBCI/OpenBCI_GUI/files/1409286/BDF.File.zip)

I attached one of the BDF that was created.  Perhaps that helps?

Thanks,
Don

**Comment by GeneralFox2** [comment]
Sorry, forgot the usual disclaimer:
I'm using a standard HP Pavilion.  Nothing special - no additional cards.  Windows 10.   Intel i5 6400T 2GHz with 12GB RAM.  

No funky anything - latest drivers from HP - Microsoft forces all patches now.....

Always works fine with OpenBCI format.

**Comment by GeneralFox2** [comment]
Hi,

Steps to resolution:
1) I am running 3.2.0
2) I noticed steps missing in the upgrade files - we are clear as to where to put the files but there is no indication of the requirement to set admin privilege  to the files when run.

New problem:  GUI freezes when file is selected for playback.  
![image](https://user-images.githubusercontent.com/32853996/34363202-f44285c8-ea47-11e7-9f7e-00e72c7cad23.png)

Clicking close exits the application after waiting for a few minutes.  GUI is non-responsive.

Thanks,
Don

**Comment by GeneralFox2** [comment]
Hi,

The BDF file will not play.  I just tried to open it in EDF Browser, and I received the following error:
![image](https://user-images.githubusercontent.com/32853996/34363324-09e3602c-ea49-11e7-911b-6869c3e9c626.png)

Sorry - case is not closed!

Don

**Comment by aj-ptw** [comment]
We are working on moving the BDF+ writing over to the OpenBCI Hub and using an open source community supported EDF writer, [node-edf](https://github.com/NeuroTechX/node-edf) because EDF is just too tough to maintain in this repo.

**Comment by retiutut** [comment]
BDF files can be produced, but they need some work to be usable. Closing this issue.
