### ISSUE TITLE
ADD: Board Mode Selection

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI#271]
Originally from #264 and @gerrievanzyl

Feature description:
Add one extra selection to the GUI before "Start System" to allow the user to set the Board mode (Accel, TimeSync, Marker, etc)

**Comment by gerrievanzyl** [comment]
This is addressed by AJs changes to the widgets and the new W_MarkerMode widget.

Tested and working.  AJ, I need your genius in tying up the marker information in the Aux channel to the currentXvalue in W_MarkerMode

Then we can close this

**Comment by aj-ptw** [comment]
@gerrievanzyl try the new hub

**Comment by gerrievanzyl** [comment]
Thanks! Will test in the next 2 hours!!!
