### ISSUE TITLE
BUG: Setting 8 channels on daisy cyton

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#282]
Steps to reproduce:

1. Attach wifi shield to daisy (16 channel cyton)
2. Launch gui 
3. Select cyton
4. Select wifi shield 
5. Pick wifi shield
6. hit start system
Now the gui will fail and say
"Wifi shield is connected to daisy but you specified cyton..."
7. Select 16 channels
8. Select start system

Boom there is the bug(s)!

There will be only eight channels showing and "START SYSTEM" is showing instead of "STOP SYSTEM"

**Comment by retiutut** [comment]
Seems to work in the current GUI.
