### ISSUE TITLE
Simultaneous data acquisition  from multiple wifi shield through GUI

### ISSUE THREAD

**Issue by msmadan** [OpenBCI/OpenBCI_GUI#288]
New feature request 

I have 2 wifi shields each one connected to 16 channel Cyton +daisy board.
I would like to request Simultaneous data acquisition  from multiple wifi shields through GUI,

Thanks
Raja

**Comment by aj-ptw** [comment]
This is going to have to be part of the Hub too.

**Comment by retiutut** [comment]
Ready to help with UI/UX for this feature using "super widgets"
