### ISSUE TITLE
Ganglion BLE Connect MAC High Sierra

### ISSUE THREAD

**Issue by wyojustin** [OpenBCI/OpenBCI_GUI#299]
## Problem

When I click
System Control Panel --> Live (From Ganglion) --> BLE (on Win from dongle)

in the GUI I see the ganglion device named "Ganglion-15c"

I click the device name and "start system".  Then the GUI hangs. 

## Expected 

I expect the GUI will display a play button.

## Operating System and Version

macOS High Sierra

## GUI Version
3.2

## Running standalone app

I am running the downloaded app

## Type of OpenBCI Board
Ganglion

Are you using a WiFi Shield?
No

**Comment by aj-ptw** [comment]
The name is “Ganglion-15c”?? There should be four numbers/letters at the end and right away that seems troubling.

**Comment by wyojustin** [comment]
Correct.  I missed the last character.

Ganglion-15c0

**Comment by aj-ptw** [comment]
Okay great, thanks so much for the clarification.

Does any message get displayed on the bottom of the GUI? 

What is the exact version number of your OS?

**Comment by wyojustin** [comment]
Message on bottom of screen: "Ganglion Device Name = Ganglion-15c0"
When it starts up it says "3.2.0"

**Comment by aj-ptw** [comment]
> What is the exact version number of your OS?

Could you [follow this guide](https://support.apple.com/en-us/HT201260) to get your macOS version number?

**Comment by wyojustin** [comment]
OSX 10.13.2 High Sierra

**Comment by trevyn** [comment]
I also experienced this problem on macOS 10.12.6 -- Ganglion appears in the BLE device list, but "Start System" hangs the GUI.

Selecting "BDF+" instead of "OpenBCI" for the data log file format works and allows streaming. Then, clicking "Stop System" under "System Control Panel" causes a hang.

**Comment by aj-ptw** [comment]
@trevyn Did you put the application in your 'Applications' folder?

**Comment by trevyn** [comment]
Ah yes, moving to Applications resolves the issue.
