### ISSUE TITLE
GUI does not start hub on windows

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#300]
## Problem

Because of permissions, the hub has to be ran as admin on windows

## Expected 

I want to launch the GUI and the windows OpenBCIHub be started

## Operating System and Version

Windows

## GUI Version

3.x.x

## Running standalone app

Yes and no.

## Type of OpenBCI Board

Cyton/Cyton+Daisy serialport driver is main problem
Also effect ganglion

**Comment by retiutut** [comment]
Test using Windows 10, Processing 3, and latest OpenBCIHub:

- Install Hub to correct location http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-running-the-openbci-gui-from-the-processing-ide-install-openbci-hub-on-windows

- Set Hub to Run as Administrator

- Set Processing to Run as Administrator

- Run the following sketch
```
Process nodeHubby;

void setup() {
  String winCmdLineHubString = "C:"+File.separator+"Program Files"+File.separator+"OpenBCIHub"+File.separator+"OpenBCIHub.exe";
  try {
    nodeHubby = exec(winCmdLineHubString);
  } catch (Exception e) {
    e.printStackTrace();
  }
}

void draw(){

}
```
