### ISSUE TITLE
3.2.0 No openBCI board attached to Wifi Shield

### ISSUE THREAD

**Issue by jnsu** [OpenBCI/OpenBCI_GUI#303]
## Problem

GUI app finds the wifi shield but its configuration tells me "No openBCI board attached to Wifi Shield."
Nothing happens when I click on 'Start System.'

## Operating System and Version

macOS 10.13.1

## GUI Version

3.2.0

## Running standalone app

Downloaded app or are you running from Processing 3

## Type of OpenBCI Board

Ganglion

**Comment by aj-ptw** [comment]
Did you update firmware on your Ganglion? If yes,
Are you powering the WiFi shield prior to Ganglion?
Is the EXT PWR switch in the off position?
Are you using two batteries?

**Comment by jnsu** [comment]
Hi Aj,
After I updated the firmware, the issue was resolved.
Thanks!
