### ISSUE TITLE
ADD: WiFi with low battery sends no data message

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#304]
## Problem

1. The GUI connects to WiFi shield with Cyton and Ganglion. 
2. Press start stream
3. No data comes out

## Expected 

I want to see an error message that my battery is low 

## Operating System and Version

macOS/Windows/Linux

## GUI Version

3.2.0

## Running standalone app

Downloaded app or are you running from Processing 3

## Type of OpenBCI Board

Cyton/Cyton+Daisy/Ganglion

## Are you using a WiFi Shield?

Yes

**Comment by retiutut** [comment]
https://openbci.com/forum/index.php?p=/discussion/2127/measure-battery-level#latest
