### ISSUE TITLE
FEATURE REQUEST: Playback SD card converted data

### ISSUE THREAD

**Issue by drjcode** [OpenBCI/OpenBCI_GUI#307]
## Problem

Converted SD card data using the processing GUI.  When trying to load the resulting converted data for playback by the GUI - getting an Array out of bounds/EEG Processing Error

I am including both the raw data file and the converted file

[OBCI_09.TXT](https://github.com/OpenBCI/OpenBCI_GUI/files/1624103/OBCI_09.TXT)

[SDconverted-2018-01-10_19-35-57.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/1624115/SDconverted-2018-01-10_19-35-57.txt)

## Expected 

See playback of the SD card data in the GUI.

## Operating System and Version

Windows 10 Pro

## GUI Version

December 2017 release

## Running standalone app

Processing 3

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?
No

**Comment by aj-ptw** [comment]
This is not a feature of the GUI and needs to be made. I think the SD card converter could use the same header as the OpenBCI output file format and then this feature would work!

Would you be interested in coding it up?

**Comment by aj-ptw** [comment]
WIll need to add some info to the converted data file such as 

* Sample rate
* Number of channels

We could ask for this data when the file is first converted so the header is populated.

**Comment by GeneralFox2** [comment]
Hi,

I would second the need for this.  I have no way of comparing the output of my MATLAB against the GUI because it won't play these recordings.

Thanks,
Don

**Comment by ahsanic** [comment]
I think I have the same issue, this is the error in OPENBCI GUI latest versions, It doesnt play playback file.

**Comment by retiutut** [comment]
@daniellasry This issue can be closed.

**Comment by GeneralFox2** [comment]
Hi, 

Does this mean that the feature was implemented? 

Thanks,
Don

----------------------------------------------------- 

On 2019-04-06 7:51 pm, Daniel Lasry wrote:

> Closed #307 [1]. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/OpenBCI/OpenBCI_GUI/issues/307
[2] https://github.com/OpenBCI/OpenBCI_GUI/issues/307#event-2257708101
[3]

**Comment by retiutut** [comment]
Yes.
