### ISSUE TITLE
Sub-options does not show when clicking "LIVE (from Cyton)"

### ISSUE THREAD

**Issue by rcsofficial** [OpenBCI/OpenBCI_GUI#310]
When I click the "LIVE (from Cyton)" option, it doesn't do anything. The error message below says I should open the OpnBCI Hub prior to launch of OpenBCI GUI despite the fact that OpenBCI Hub is actually running before I ran the GUI. I did run the Hub as an administrator yet nothing happens.

I am using a 64-bit Windows 8 desktop. Weird enough, the GUI works okay on my 64-bit Windows 10 laptop.

UPDATE: When I installed LabView on my laptop, the same thing happened. I can no longer click the "LIVE (from Cyton)" option. The Windows 8 desktop where this first happened had LabView installed with it before I installed the OpenBCI GUI and Hub.

![image](https://user-images.githubusercontent.com/33612519/35423641-ca4af99e-0289-11e8-831d-8ec58f828c1a.png)

**Comment by aj-ptw** [comment]
Maybe Labview is using the same port number as the OpenBCI Hub. Does any error come up when the hub is launched?

**Comment by rcsofficial** [comment]
No errors show up when the hub is launched. I tried uninstalling the
LabView but the GUI won't allow me to click the "Live from Cyton" anymore.
Prior to the LabView install, everything in the GUI worked fine for my
Windows 10 laptop.

Yours truly,

*Richmond Sim*
Academic: richmond.sim@obf.ateneo.edu
Personal: sim.richmond@gmail.com
General Mobile: +63 915 971 8434 / +63 929 723 4504

**Comment by aj-ptw** [comment]
Do you think you could try running the GUI from processing? This will print out the errors the GUI is running into.

Sorry for these troubles!

**Comment by rcsofficial** [comment]
I did try to run it using Processing and after a couple of library fixes
required, the GUI still did not run. I will respond back to check the exact
code in the console after I get back to my work station

**Comment by rcsofficial** [comment]
I followed all instructions in your documentations and tried three
different computers. I am stuck here:

[image: Inline image 1]

The play button is green but the GUI does not appear. I've already waited
30 minutes to no avail.


Yours truly,

*Richmond Sim*
Academic: richmond.sim@obf.ateneo.edu
Personal: sim.richmond@gmail.com
General Mobile: +63 915 971 8434 / +63 929 723 4504

**Comment by SoatOfficial** [comment]
I have the same problem, but when i click on " LIVE (from cyton) " the console show me "click"

**Comment by aj-ptw** [comment]
What version?

**Comment by SoatOfficial** [comment]
![screen](https://user-images.githubusercontent.com/10077803/35992445-91a56ff8-0d0a-11e8-85fa-7753654c1358.png)

**Comment by aj-ptw** [comment]
Is there an OpenBCIHub in your _data_ folder?

**Comment by SoatOfficial** [comment]
No there isn't

![schermata 2018-02-08 alle 21 07 25](https://user-images.githubusercontent.com/10077803/35995587-1e52ad18-0d14-11e8-83ad-4f228dabdc23.png)

**Comment by aj-ptw** [comment]
You just need to drag and drop the [openbci hub](https://github.com/OpenBCI/OpenBCI_Hub)

Latest release is v1.3.9
https://github.com/OpenBCI/OpenBCI_Hub/releases/tag/v1.3.9

**Comment by aj-ptw** [comment]
I believe i have solved these issues, please let me know if there is anything else needed.!
