### ISSUE TITLE
i have 8bit board it's not working with OPENBCI new version

### ISSUE THREAD

**Issue by Baghdady92** [OpenBCI/OpenBCI_GUI#311]
## Problem

i have 8bit board it's not working with OPENBCI new version
is there any support ? to make it work 
thank you

**Comment by aj-ptw** [comment]
There is no support for this :/ Please try to use an older version of the GUI, pre 2.0 I believe

**Comment by aj-ptw** [comment]
I'm closing for now because this is an unsupported board for this repository.
