### ISSUE TITLE
OpenBCI_GUI does not find Ganglion BLE signals

### ISSUE THREAD

**Issue by Christoph98** [OpenBCI/OpenBCI_GUI#312]
## Problem

I'm trying to connect the Ganglion to my MacBook Air (Version 10.9.5), I have Wi-Fi and Bluetooth enabled, but it doesn't find anything in the BLE search. In fact, the entire BLE search is a bit weird; it doesn't consistently start searching by itself when I click on BLE. If I go onto the Wi-Fi button (below the BLE option), it immediately starts searching, every time. Then, if I go to BLE it will continue searching. So I'm thinking it might be something wrong with the BLE option as a whole. The Wi-Fi seems to work fine (although I cannot connect to anything).

## Expected 

I hope there is some sort of simple fix, that I can do. I had the GUI in my applications folder, I have also tried running it through processing, but they both bring me the same problems to solve...

## Operating System and Version

macOS 10.9.5

## GUI Version

The most updated version.

## Running standalone app

Running from Processing 3 and the application itself, neither work.

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

Not using a WiFi Shield.

**Comment by aj-ptw** [comment]
That's an older version of macOS that I don't have access too, maybe that is the problem.

**Comment by aj-ptw** [comment]
@Christoph98 I think i have a solution for you! You should buy a BLED112 dongle and use this on your mac book pro. Please verify the BLED112 dongle can support such an operating system, but the Ganglion driver for BLED112 is in beta and too be released soon! You cannot rely on native drivers with the outdated operating system.

**Comment by Christoph98** [comment]
Thank you @aj-ptw, unfortunately I don't have the Ganglion anymore (I was borrowing it). Best of luck!
