### ISSUE TITLE
Using the standalone OpenBCI GUI to stream via LSL freezes the application

### ISSUE THREAD

**Issue by sidharthanup** [OpenBCI/OpenBCI_GUI#318]
## Problem

The LSL stream freezes in the standalone GUI and when I ran the GUI using Processing and clicked on Live(from Ganglion) it gives an error "Please launch OpenBCI Hub prior to launching this application". Is there a fix to this?

## Operating System and Version

Windows 10

## GUI Version

OpenBCI GUIv3.2.0

## Type of OpenBCI Board

Ganglion

**Comment by aj-ptw** [comment]
Yup follow the tutorial:
http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-running-the-openbci-gui-from-the-processing-ide

**Comment by sidharthanup** [comment]
But I did exactly as it was instructed. I ran theOpenBCI Hub before running the GUI via processing and still the same error.
