### ISSUE TITLE
Networking in LSL error (macOS)

### ISSUE THREAD

**Issue by compmonks** [OpenBCI/OpenBCI_GUI#320]
## Problem

Following similar issues on other platforms (ex: https://github.com/OpenBCI/OpenBCI_GUI/issues/317), an error freezes the GUI when trying to stream data with LSL. This is happening in my case on mac OS:

`
_LSL selected from Protocol Menu

openBCI_GUI: startButton was pressed...starting data transfer...

startRunning...

DEBUG: start data transfer

Cyton: startDataTransfer(): writing 'b' to the serial port...

Hub: sendCommand(char): sending 'b'

Hub: processCommand: success -- 41664

Stream update numChan to 16

nPointsPerUpdate 5

dataToSend len: 80

[TimeSeries, obci_eeg1, EEG, 16, 1]

java.lang.UnsatisfiedLinkError: Unable to load library 'liblsl64.dylib': Can't obtain InputStream for darwin/liblsl64.dylib
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:408)
	at java.lang.Thread.run(Thread.java:748)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application._
`

## Expected 

LSL stream output

## Operating System and Version

oSX High Sierra 10.13.3

## GUI Version

3.2.0 Dec 2017

## Running standalone app

running from Processing 3

## Type of OpenBCI Board

Cyton+Daisy 16 chan

## Are you using a WiFi Shield?

No

**Comment by aj-ptw** [comment]
Did you put the libraries into your local folder?

**Comment by daniellasry** [comment]
fixed
