### ISSUE TITLE
BUG: Autoscan on Windows 7 does not work

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#322]
## Problem

Autoscan does not work to pair the radios together, continues to show Failure: System is Down message

## Expected 

Pressing autoscan should **always** realign the channel settings

## Operating System and Version

Windows 7

## GUI Version

3.2.0

## Running standalone app

Standalone app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
@daniellasry I think this issue can be closed, I believe Autoscan is working.
