### ISSUE TITLE
OpenBCI_GUI can't find ganglion

### ISSUE THREAD

**Issue by kallander** [OpenBCI/OpenBCI_GUI#323]
## Problem
I'm trying to connect the ganglion to the openBCI_GUI_processing, but it can't connect to the ganglion.  When i use the stand alone program or BrainBay the connection works perfect.
I've installed the 3.3.6 version of Processing and everything is where it should in the folders (i think, according to the guide here https://github.com/OpenBCI/OpenBCI_Processing ). The GUI_processing works if I use a synthetic source instead so it's just the connection to the ganglion that's missing.. 
When trying to connect I get this error: 
map(17.10527, 0, 0, 0, 0) called, which returns NaN (not a number)

## Operating System and Version

Windows 10 

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by kallander** [comment]
![image](https://user-images.githubusercontent.com/35805112/38413133-31e4810a-398b-11e8-90e1-943ec999b71e.png)

**Comment by aj-ptw** [comment]
That's the version of the GUI before ganglion was support. Please follow [this OpenBCI GUI tutorial](http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI). I'm closing this issue.

**Comment by aj-ptw** [comment]
Use the code in this repository
