### ISSUE TITLE
BIAS no longer included

### ISSUE THREAD

**Issue by emolyzr** [OpenBCI/OpenBCI_GUI#334]
## Problem

Started streaming with BIAS "included". Sometimes after a while all channels will show 0,10µV, but are still running and reacting. A look to the hardware settings reveals that BIAS has changed to "Don't include". Don't know how this happened. Already encountered this problem multiple times. May I accidentally pressed a short cut do exlcude BIAS?

## Expected 

This should better not happen.

## Operating System and Version

WIN 10 64bit PRO v1709

## GUI Version

December2017, v3.2.0

## Running standalone app

app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
Using the current keyboard shortcuts, disabling a channel in the Time Series widget will automatically turn Bias to "Don't Include" and SRB2 to "Off". Similarly, turn the channel back back on _this time using the shift key + keyboard shortcut_ and Bias will change to "Include" and SRB2 to "On". However, it seems that pressing the channel button on and off _does not affect_ Bias and SRB2 options.

**Comment by retiutut** [comment]
There are some old lines of code in BoardCyton that mention biasAuto and biasFixed, but it says they are "now depreciated". These shortcuts don't appear in Interactivity and seem to have been removed for some good reason. Also, not sure what they used to do, just that it had to do with Bias.

https://github.com/OpenBCI/OpenBCI_GUI/blob/16129254c346c5f21d930f4d29657a70c7c9d686/OpenBCI_GUI/BoardCyton.pde#L52

https://github.com/OpenBCI/OpenBCI_GUI/blob/16129254c346c5f21d930f4d29657a70c7c9d686/OpenBCI_GUI/BoardCyton.pde#L53

**Comment by emolyzr** [comment]
First: To use the shortcuts correctly, you need to use the ENG keyboard Layout. My GER layout produced strange outcomes.
Second: Using the shortcuts for activation and deactivation consistently will change BIAS and SRB2 ... *as long as you didn't make any manual changes in these hardware settings*. As soon as you set BIAS to "Don't include" yourself, using shortcuts won't affect BIAS and SRB2. BUT... acutally it seems that these shortcuts are not reliably changing SRB2 and BIAS, e.g. if I press "1" for deactivating channel 1, then BIAS and SRB2 turn to off. I "accidentally" press "1", channel 1 ist still deactivated and SRB2 and BIAS didn't change. I reactivate channel 1 by pressing SHIFT + 1, but SRB2 and BIAS don't change.

However, this doesn't seem to speak to my problem. Because channel 1 is activated the whole recording and only BIAS seems to switch from "Include" to "Don't include"... so it's not accidentally deactivating a channel by using shortcuts. But as you said there aren't dedicated shortcuts for changing the BIAS, right?

**Comment by retiutut** [comment]
The only keyboard shortcuts that appear to be active are those in OpenBCI_GUI/OpenBCI_GUI/Interactivity.pde . I am experiencing the same weird control issues, and I'm using v3.3.1 development branch. @emolyzr maybe try updating to v3.3 April 2018 or newer.

Would adding a shortcut to make "all BIAS to Include" across all channels help? I can possibly try to add a shortcut.
I've identified the lines of code in HardwareSettingsController starting here:
https://github.com/OpenBCI/OpenBCI_GUI/blob/16129254c346c5f21d930f4d29657a70c7c9d686/OpenBCI_GUI/HardwareSettingsController.pde#L127

**Comment by retiutut** [comment]
I've created a shortcut to turn Bias On all channels using the lowercase 'L' key! 

Let me see if I can fix this channel keyboard shortcut mixup.

**Comment by retiutut** [comment]
![screen shot 2018-05-21 at 6 49 53 pm](https://user-images.githubusercontent.com/25914123/40335141-cc4ab2ae-5d27-11e8-84d0-a4ca9b2e9710.png)
![screen shot 2018-05-21 at 6 49 53 pm](https://user-images.githubusercontent.com/25914123/40335144-d0378932-5d27-11e8-9595-9a0d23ab58a7.png)

**Comment by retiutut** [comment]
![screen shot 2018-05-21 at 7 01 01 pm](https://user-images.githubusercontent.com/25914123/40335487-839383cc-5d29-11e8-8346-26f49ade4a26.png)

![screen shot 2018-05-21 at 7 01 01 pm](https://user-images.githubusercontent.com/25914123/40335490-8a76e76a-5d29-11e8-95d1-27390d59532b.png)

**Comment by retiutut** [comment]
![screen shot 2018-05-21 at 7 01 01 pm](https://user-images.githubusercontent.com/25914123/40335495-98884dda-5d29-11e8-8fe0-f53bf1553b4f.png)
![screen shot 2018-05-21 at 7 01 23 pm](https://user-images.githubusercontent.com/25914123/40335497-9bc57766-5d29-11e8-8b24-88e0e8431efb.png)

**Comment by retiutut** [comment]
@emolyzr I see the problem with the channel shortcuts with the German Keyboard vs English Keyboard! The issue is with the top row of numbers when Shift key is pressed. I was able to learn this here http://ascii-table.com/keyboard.php/129

**Comment by retiutut** [comment]
@daniellasry This issue was also resolved quite some time ago.

Heads up, there may be a few more issues I can recommend for final review and closure.

**Comment by daniellasry** [comment]
@retiutut thanks! yes, please do recommend any issues you think should be closed or looked at.
