### ISSUE TITLE
OpenBCI_GUI 3.3.1 macos release doesn't have the Hub in the data folder

### ISSUE THREAD

**Issue by dyfer** [OpenBCI/OpenBCI_GUI#335]
## Problem

After starting OpenBCI_GUI 3.3.1 downloaded from the releases page and selecting Live Cyton, it displays message that it can't connect to the hub. Upon further investigation it seems that the Hub application is not in the right place in the application package - it is in `Contents/Java` but it should be (I think) in `Contents/Java/data`.

## Expected 

OpenBCI_GUI should start the hub; or the hub should be placed in the proper folder in the application package

## Operating System and Version

macOS

## GUI Version

3.3.1

## Running standalone app

Standalone

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

Yes

**Comment by aj-ptw** [comment]
Fixed! Thanks!
