### ISSUE TITLE
Accelerometer display pops up error then only gives 0 value readings

### ISSUE THREAD

**Issue by x37v** [OpenBCI/OpenBCI_GUI#338]
## Problem

The accelerometer display pops up error and displays 0 for all 3 axes.

Reproduction steps:

1) start the gui
2) connect to board and start
    * we used the computer's internal BLE
3) select the accelerometer display tab
4) click "turn accel on"

You should now see an error popup window: 

`OpenBCIHub Fatal Error`
`"list" must be an Array of Bufers`

<img width="1280" alt="accelerometer" src="https://user-images.githubusercontent.com/65796/41016566-001bc954-6905-11e8-85d7-25d810e80a4a.png">

5) click "ok" on the error popup
6) click "Start Data Stream"

We see only 0 for the 3 accelerometer values.

## Expected 

We would expect no error popup and valid accelerometer readings.

## Operating System and Version

macOS 10.12.6

## GUI Version

3.3.0

## Running standalone app

standalone

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by aj-ptw** [comment]
Working on a patch for this bug!

**Comment by x37v** [comment]
Fantastic! Thanks @aj-ptw
