### ISSUE TITLE
DOCS: Marker mode docs for Cyton

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#341]
## Problem

No information on how to use the markers.

## Expected 

To get information on how to use the markers, maybe even a python file that shows how the markers work.

## Operating System and Version

macOS/Windows/Linux

## GUI Version

v3.1.1

**Comment by superabe** [comment]
The same question I want to know.

**Comment by leevonk** [comment]
ditto

**Comment by neurofoo** [comment]
bump

**Comment by KevMCh** [comment]
Has anyone found something about that?

**Comment by retiutut** [comment]
https://openbci.com/community/v3-0-0-cyton-firmware-now-available/
