### ISSUE TITLE
Itermittent Connection with Cyton Board

### ISSUE THREAD

**Issue by arduinosphere** [OpenBCI/OpenBCI_GUI#344]
## Problem
When firing up the gui, it will sometimes allow me to begin streaming (often upon restarting my computer or after time has passed) while usually, it will be unable to find my cyton board and return : init timeout. very your serial/com port. Power DOwn/Up your openbci & USB Dongle. Then retry Initialization. 

Also finding trouble connecting via Open_BCI LSL
Because it sometimes does work well, I don't think it's some simple user error on my end.  Hardware problems? Common issue?

Windows 10
Gui v3.2
Running Downloaded App
Cyton + Daisy
No Wifi Shield

**Comment by daniellasry** [comment]
We believe this to be fixed in 4.1.2 beta. Please comment if not the case
