### ISSUE TITLE
USB not selecting com port

### ISSUE THREAD

**Issue by dib1205** [OpenBCI/OpenBCI_GUI#346]
## Problem
My problem is, when I am clicking on openBCIhub icon nothing is opening. When I am clicking on OpenBCIGUI and selecting Cyton option, then serial from dongle it is showing nothing. I checked for the COM port by going to device manager, it is not showing anything in terms of COM port selected by the USB.
## Operating System and Version

Windows 10

## Running standalone app

Are you running the downloaded app

## Type of OpenBCI Board

Cyton
## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
@daniellasry This issue can be closed.
