### ISSUE TITLE
GUI Rendering delay causes artifact pulses on Widgets

### ISSUE THREAD

**Issue by MobileRez** [OpenBCI/OpenBCI_GUI#349]
## Problem

While using the Open BCI Gui with the Time Series, Band Power, & Head Plot widgets I would get random artifact data in the device across all channels and all configurations. This is also duplicatable when just using the head plot widget.

Noticed there is no system setting to set recourse priority with the APP, this is causing it to not be able to access all the resources it needs, not sure if the fact its build with java has any impact with that, though would explain the unreasonable high demand on resources.  

**EDIT 7/3/18** 
Added Links to images showing reported issue.
[Photo of Device and wired electrodes](https://1drv.ms/u/s!AiutdRJAvNiliLcmYWGjHe1J9aI1OA)
[Photo of GUI W/ reported bug noise](https://1drv.ms/u/s!AiutdRJAvNiliLchOeEtwP7W7EWDYA)
[Photo of Closeup of bug on all channels](https://1drv.ms/u/s!AiutdRJAvNiliLckEr3Glv4BPxoHcw)

## Expected 

No artifact nose is GUI from rendering issues, able to control System Resource priority from software as later versions of Win 10 do not let you set it from task manager therefor you cannot access all system resources as needed.

## Operating System and Version

Windows 10 Pro x64
Version: 1709
Build: 16299.431

## GUI Version

3.3.1

## Running standalone app

Running in OpenBIC GUI 

## Type of OpenBCI Board

Cyton running firmware v3.1.1

## Are you using a WiFi Shield?

No - But I would like to.

**Comment by andrewjaykeller** [comment]
Okay so this is all because of the headplot :(

Did you try changing the smoothing at all? I think the headplot needs to be rewritten!

**Comment by MobileRez** [comment]
Yes and no setting I could use on that Head Plot graph could help smooth things out. I know most people would call my surface book (1) with performance base old by now but its got some decent power too it and a decent graphics card as well so it should be able to handle this rendering... that must be some really bad code...

**Comment by paquettejp** [comment]
Hi,

Wondering if there has been any development on this issue? It seems to be similar, if not the same issue as: https://github.com/OpenBCI/OpenBCI_GUI/issues/231

I am using a Cyton with WiFi Shield (firmware, 2.0.5) and I have also noticed these intermittent bursts of noise in my recordings. I am running the OpenBCI standalone GUI (Version 3, 4.0.3) on OS X 10.13.6.

To check the FPS issue, I used the Time Series and Head Plot separately with the Widget Template and Marker Mode. The Time Series seemed to stay in the high 50s but the Head Plot got down to 10 FPS.

In both cases, I observed this burst noise.

**Time Series:**
![time_series](https://user-images.githubusercontent.com/48809957/55907917-0d754a00-5ba6-11e9-8960-4420a652c25b.png)

**Head Plot:**
![head_plot](https://user-images.githubusercontent.com/48809957/55907916-0d754a00-5ba6-11e9-881e-4be5b03809ec.png)

**Comment by retiutut** [comment]
It’s packet loss related to the WiFi shield and Cyton, hardware related. Issue is described in detail already. #231

**Comment by retiutut** [comment]
@paquettejp the issue here, about Headplot FPS, is definitely on the table to be fixed soon!

**Comment by paquettejp** [comment]
> @paquettejp You are experiencing packet loss related to the WiFi shield and Cyton, hardware related. Issue is described in detail already. #231 The team is definitely aware of this and we are still working on a plan of action, up to designing new hardware.
> 
> This issue here is likely caused by Headplot widget being greedy, so not related to packet loss.

Thank you for clearing that up! Two separate issues.
