### ISSUE TITLE
Array Index Out Of Bound : Exception

### ISSUE THREAD

**Issue by HamzaHummam** [OpenBCI/OpenBCI_GUI#368]
## Problem
I am facing Exception : Array Index Out Of Bound When Loading a Playback File
The exception is referred to occur in the Data Processing file in the following line 
File Name : Data Processing 
Line No  272 :  fooData = Arrays.copyOfRange(fooData, fooData.length-Nfft, fooData.length);

I am using this file as playback file [openBCI_2013-12-24_meditation.txt](https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/SavedData/Sample_Data/openBCI_2013-12-24_meditation.txt)
Debug Logs:
%OpenBCI Raw EEG Data % %Sample Rate = 250.0 Hz %First Column = SampleIndex %Other Columns = EEG data in microvolts
OpenBCI_GUI: initSystem: loading complete. 125130 rows of data, which is 2147483647 seconds of EEG data
OpenBCI_GUI: initSystem: Initializing core data objects
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
OpenBCI_GUI: initSystem: -- Init 1 -- 26265
OpenBCI_GUI: initSystem: Initializing FFT data objects

## Expected 

It should play the playback file without any errors, which shows the EEG saved data in the OpenBCI Software.

## Operating System and Version

Windows 10

## GUI Version

3.4.0
## Running standalone app

running from Processing 3

## Type of OpenBCI Board

Cyton, but it shouldnt matter because I am trying the playback file.

## Are you using a WiFi Shield?

Yes
But again it shouldnt matter.

**Comment by retiutut** [comment]
**Please close this thread. I have solved this issue already in another duplicate thread.** https://github.com/OpenBCI/OpenBCI_GUI/issues/348

> You will get this same error when using sample EEG playback files because they are old. There is already an issue to fix this. #315
