### ISSUE TITLE
GUI 3.3.2 at Windows 7 cause error 412 with Ganglion

### ISSUE THREAD

**Issue by Barba2DOS** [OpenBCI/OpenBCI_GUI#373]
## Problem

1) GUI 2.2.1 works fine, Ganglion detected via CSR4.0 USB dongle with WinUSB driver
2) GUI 3.3.2 echoes Error 412 if I use 3.3.2 hub. And it not display Ganglion in BLE device list.
3) If I ran GanglionHub from 2.2.1 then gui 3.3.2 got ganglion in BLE dev list and works fine.

Issue tested with PC and laptop. Both with Windows 7 x64

## Expected 

Hope that if 2.2.1 works fine  3.3.2 should works too

## Operating System and Version

Windows 7 x64

## GUI Version
3.3.2

## Running standalone app
I running the downloaded app 

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
@daniellasry This issue can be closed.
