### ISSUE TITLE
Widget: Playback Functionality

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#38]
New features for playback

- [ ] Slider on bottom of time series plot
- [ ] Total time and slider like watching a youtube video

**Comment by retiutut** [comment]
@andrewjaykeller This issue has been resolved by developing a **functional playback slider sub-widget** that appears during playback. A branch has been made off the development branch:
https://github.com/retiutut/OpenBCI_GUI/tree/playback-ts-scrubbing

**Comment by retiutut** [comment]
![openbci-2018-08-03_21-54-09](https://user-images.githubusercontent.com/25914123/43671875-d85cf8ac-9767-11e8-9742-7bce2732842f.jpg)

**Comment by retiutut** [comment]
![openbci-2018-08-04_12-44-14](https://user-images.githubusercontent.com/25914123/43679068-29c18786-97e4-11e8-9872-8f1863bbb823.jpg)

**Comment by daniellasry** [comment]
It looks like this feature has been implemented successfully. Verified in 4.0.3 
Feel free to open separate issues for any enhancements regarding the playback slider.
