### ISSUE TITLE
Problems with my cyton on GUI

### ISSUE THREAD

**Issue by FranckDomingues** [OpenBCI/OpenBCI_GUI#384]
## Problem

I tried to do a scan of my signals, I connect Bias 1, N7P, N2P, SRB1, I connect all on the down pins, my cyton is chipKIT from china, this version is wired, don't have any BLE, SD, is basic board. 

![image](https://user-images.githubusercontent.com/22613985/45946101-b8962b80-bfe7-11e8-9157-9b1b16336bc6.png)

But when I put the sensor on my head and ears, I just receive from the cyton noise, I use 50Hz because I'm in Europe, like this picture,

![image](https://user-images.githubusercontent.com/22613985/45946209-280c1b00-bfe8-11e8-98c6-44d7d09dbfa8.png)

![image](https://user-images.githubusercontent.com/22613985/45946544-18d99d00-bfe9-11e8-8ffe-65d8784dba96.png)

I tried to do differents configurations on GUI but is like the same thing, just noise, even tried with 60Hz, the board is into an anti-static bag, I need help, I'm working with this on my master thesis about sleep monitoring. on Mac is the same, I think maybe to update the board but, I don't know which one firmware is the best to use. I have the TEN20 paste for the conductivity.

Thanks.

## Expected 

Some help about, is correct to update the board which firmware is better to use, or tried with a particular configurations.

## Operating System and Version

macOS/Windows/

## GUI Version

the last version for June 2018

## Running standalone app

I'm running the downloaded app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No, just USB cable like the Dongle.

**Comment by daniellasry** [comment]
@FranckDomingues I'm sorry, it looks like the board you have is a clone/fake. It was not manufactured by OpenBCI. It probably was not meant to work at all. If it's not too late, I would contact the original manufacturer and try to return it. Failing that, try to get a chargeback on the transaction.
