### ISSUE TITLE
OpenBCI GUI v3.3.2 freezes when "start system" on Windows and USB dongle light stops

### ISSUE THREAD

**Issue by bciuser** [OpenBCI/OpenBCI_GUI#388]
## Problem

OpenBCI GUI freezes when I click "start system" (on Windows) - and USB dongle light stops. This is my first time using this device. I already installed the FTDI, and followed all the instructions online.

1. Before I hit "start system"- it finds the COM and everything seems OK:
![dongleon](https://user-images.githubusercontent.com/44125584/46910577-f3b7ba80-cf14-11e8-984e-680ac63d1118.PNG)
![capture](https://user-images.githubusercontent.com/44125584/46910591-08944e00-cf15-11e8-96e2-40f8d4e8f0c8.PNG)

2. Then after I hit 'start system' the GUI freezes and the USB dongle light turns off
![dongleoff](https://user-images.githubusercontent.com/44125584/46910574-ee5a7000-cf14-11e8-8af4-8d2ceea6fe48.PNG)

## Expected 

I hit "start system" and data starts streaming and displaying on the GUI

## Operating System and Version

Windows 10 enterprise, 2018 (64 bit)

## GUI Version

v3.3.2, June 2018

## Running standalone app

Standalone app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No. I'm using the OpenBCI USB dongle

**Comment by andrewjaykeller** [comment]
Your switch on your dongle is in RESET. Please flip it!
