### ISSUE TITLE
Playing back files freezes GUI

### ISSUE THREAD

**Issue by mbmosher** [OpenBCI/OpenBCI_GUI#392]
## Problem

In the GUI, selecting PLAYBACK (from file) > SELECT PLAYBACK FILE > (OpenBCI_GUI/OpenBCI_GUI/SavedData/Sample_Data/openBCI_2013-12-24_relaxation.txt) > START SYSTEM

Nothing happens.

## Expected 

Something would happen, would see graphs and the rest of the UI appear.

## Operating System and Version

macOS 10.11.6

## GUI Version

1

## Running standalone app

Tried both, same behavior.  Processing does give an error:  
OpenBCI_GUI: initSystem: -- Init 0 -- 44713
timeOfInit = 44713
OpenBCI_GUI: initSystem: Preparing data variables...
OpenBCI_GUI: initSystem: loading playback data from /Users/ma692464/Downloads/OpenBCI_GUI-master/OpenBCI_GUI/SavedData/Sample_Data/openBCI_2013-12-24_relaxation.txt
%OpenBCI Raw EEG Data % %Sample Rate = 250.0 Hz %First Column = SampleIndex %Other Columns = EEG data in microvolts
OpenBCI_GUI: initSystem: loading complete.  125130 rows of data, which is 2147483647 seconds of EEG data
OpenBCI_GUI: initSystem: Initializing core data objects
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
EEG_Processing: *** ERROR *** Filters can only work at 125Hz, 200Hz, 250 Hz, 1000Hz or 1600Hz
OpenBCI_GUI: initSystem: -- Init 1 -- 45074
OpenBCI_GUI: initSystem: Initializing FFT data objects

## Type of OpenBCI Board

None.

## Are you using a WiFi Shield?

No.

**Comment by retiutut** [comment]
@daniellasry This is a duplicate issue.

#315
