### ISSUE TITLE
v4.0.0-alpha.2 fails at "Instantiating hub object..."

### ISSUE THREAD

**Issue by cravens1968** [OpenBCI/OpenBCI_GUI#393]
## Problem

I would like to create a new feature by branching off of the current development branch.  Unfortunately, v4.0.0-alpha.2 from the development branch fails at the "Instantiating hub object..." step.  (See paste of v4.0.0-alpha.2 console output below).  However, the stable release v. 3.4.0 from the master branch works just fine. (See paste of the 3.4.0 console output below).  The difference appears to be that v 3.4.0 completes the handshake: "Hub: clientEvent: handshake complete" . Also I can playback saved data from a file but it is not possible to connect to my Ganglion board.   Is there a known fix for this problem or should I work off of the master branch?  The release notes indicate that a similar/related bug was fixed earlier in the month ...  Any guidance would be appreciated!

## Expected 

I expected to connect to my Ganglion upon clicking the the CSR bluetooth button.  This works just fine with the stable release but does not work with the alpha.  The alpha doesn't crash but it doesn't connect either.  Not sure if this is relevant but it also seems like it crashes the hub.  I have to restart it afterwards.

## Operating System and Version

Windows 10

## GUI Version

v4.0.0-alpha.2

## Running standalone app

Running from Processing 3

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

--------------------------------------------------------------
The dump from the processing console is below.
--------------------------------------------------------------

Screen Resolution: 3840 X 2160
Welcome to the Processing-based OpenBCI GUI!
For more information about how to work with this code base, please visit: http://docs.openbci.com/OpenBCI%20Software/
Local Version: 400, Latest Version: 340
GUI is up to date!
Graphics & GUI Library: ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
attempting to load images for presentation...
DONE loading images!
OpenBCI_GUI::Setup: Is RX mulitcast: false
OpenBCI_GUI::Setup: Has RX joined multicast: false
Instantiating hub object...
click

-----------------------------------------------------------------
The dump from the console when I run the stable v. 3.4.0
------------------------------------------------------------------

Welcome to the Processing-based OpenBCI GUI!
Last update: 9/5/2016
For more information about how to work with this code base, please visit: http://docs.openbci.com/OpenBCI%20Software/
Graphics & GUI Library: ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
attempting to load images for presentation...
DONE loading images!
OpenBCI_GUI::Setup: Is RX mulitcast: false
OpenBCI_GUI::Setup: Has RX joined multicast: false
Instantiating hub object...
Hub: clientEvent: handshake complete

**Comment by andrewjaykeller** [comment]
Hey You just need to use the latest hub. I can make you one for windows ten.

**Comment by andrewjaykeller** [comment]
you should use the development branch

**Comment by cravens1968** [comment]
Thank you!  Will you email to me or publish it on github?

**Comment by andrewjaykeller** [comment]
Was this fixed in 4.0.2 release?

**Comment by retiutut** [comment]
@daniellasry This has been fixed.
