### ISSUE TITLE
The function of the CytonUserSettings.json is what?

### ISSUE THREAD

**Issue by wangjl02** [OpenBCI/OpenBCI_GUI#395]
## Problem

The GUI software connection Cyton failed
When delete CytonUserSettings.json file ,connection is ok.but I dont delete the file everytime.
If you could ask me what is the function of the file?

The SoftwareSettings.pde file some code
In this code,the errorUserSettingsNotFound is best.because dont exit CytonUserSettings.json file,the errorUserSettingsNotFound is true,then,the function dont perform.this is me want.
OK? 
Thanks
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                Load GUI Settings                                                       //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void loadGUISettings (String loadGUISettingsFileLocation) {
  //Load all saved User Settings from a JSON file if it exists
  println("loadGUISetting begin");
  if (!errorUserSettingsNotFound) {
    println("return 1");
    loadSettingsJSONData = loadJSONObject(loadGUISettingsFileLocation);
  } else {
    println("return 2");
    outputError("Load settings error: " + userSettingsFileToLoad + " not found. ");
    return;
  }
  println("loadGUISetting end");

## Operating System and Version

Windows

## GUI Version

3.4.0

## Running standalone app

running the downloaded app or are you running from Processing 3

## Type of OpenBCI Board

Cyton 

## Are you using a WiFi Shield?

Yes

**Comment by daniellasry** [comment]
CytonUserSettings.json is a file containing your settings (widget options, layout, etc) when using the cyton board. This part of the code has changed a lot sine 3.4.0. Care to try again with v4.1.2 beta and let me know how it goes?
