### ISSUE TITLE
Accelerometer axes 

### ISSUE THREAD

**Issue by jps2000** [OpenBCI/OpenBCI_GUI#398]
## Problem
Accelerometer report x, y, z axes. Rotating the Ganglion  revealed that the sign of axes are not right hand cartesian coordinates ( Turning +x into +y axis should point in +z direction (right hand screw)
## Expected 
Right hand coordinate repersentation
Hence z should  change sign or x exchanged with y

## Operating System and Version

Windows 7 professional 64bit

## GUI Version

4.0.2 ( probably in all versions)

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by jps2000** [comment]
Note that chip has flipped  pcb side between cyton and ganglion.  ( x and z axis changed sign)

**Comment by retiutut** [comment]
> Note that acc chip has changed pcb side between cyton and ganglion. 👍 

The following pictures document this issue. Cyton and Ganglion were placed side by side using GUI on two machines, then rotated in the same way. The GUI shows different results: 

- Flat and facing up
![openbci-2018-11-20_07-37-53 - cyton 1](https://user-images.githubusercontent.com/25914123/48778287-60ec0780-ec9a-11e8-841c-8dff8ab36159.jpg)
![openbci-2018-11-20_07-37-48 - ganglion - 1](https://user-images.githubusercontent.com/25914123/48778292-63e6f800-ec9a-11e8-835c-5abc2d2667d0.jpg)

- Rotation 1
![openbci-2018-11-20_07-38-24 - cyton 2](https://user-images.githubusercontent.com/25914123/48778365-97c21d80-ec9a-11e8-86b2-84cfbbf2b6ab.jpg)
![openbci-2018-11-20_07-38-19 - ganglion - 2](https://user-images.githubusercontent.com/25914123/48778371-9b55a480-ec9a-11e8-9e22-920dc90394d9.jpg)

- Rotation 2
![openbci-2018-11-20_07-38-51 - cyton 3](https://user-images.githubusercontent.com/25914123/48778379-a3addf80-ec9a-11e8-9c90-bfd123859482.jpg)
![openbci-2018-11-20_07-39-04 - ganglion - 3](https://user-images.githubusercontent.com/25914123/48778390-a9a3c080-ec9a-11e8-958e-49e811dd4870.jpg)

**Comment by jps2000** [comment]
Yeah thats what I discovered.
Assuming Cyton as the  reference, Ganglion should deliver same acc output (preferably).

**Comment by retiutut** [comment]
@andrewjaykeller Can I go ahead and fix this using Cyton as a reference?

**Comment by andrewjaykeller** [comment]
So X and Z are multiples by -1?

**Comment by retiutut** [comment]
> So X and Z are multiples by -1?

Z can be inverted for Ganglion.

X and Y may need to be swapped?

**Comment by jps2000** [comment]
Solved in 4.1.0
Thank you
