### ISSUE TITLE
GUI or Hub cannot see Ganglion, if macOS user upgrades to Mohave (10.14)

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/OpenBCI_GUI#402]
## Problem

Explain the problem

## Expected 

In a perfect world, what do you expect to happen.

## Operating System and Version

macOS/Windows/Linux

## GUI Version

The version is displayed on startup.

## Running standalone app

Are you running the downloaded app or are you running from Processing 3

## Type of OpenBCI Board

Cyton/Cyton+Daisy/Ganglion

## Are you using a WiFi Shield?

Yes/No

**Comment by wjcroft** [comment]
All GUI versions up to 4.0.2 are seeing this. Both standalone and Processing initiated. No Shield. See these threads on forum:

http://openbci.com/forum/index.php?p=/discussion/1876/no-ganglion-bluetooth-connection-after-macos-mohave-update#latest

http://openbci.com/forum/index.php?p=/discussion/1861/ganglion-on-mac-mohave-no-bluetooth-connection#latest

Regards, William

**Comment by andrewjaykeller** [comment]
Hi @wjcroft !! So nice to see you one Github! I'm working on a patch right now!

**Comment by andrewjaykeller** [comment]
Hi @wjcroft please point users to:

https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v4.0.3-beta.0

**Comment by mr-yamraj** [comment]
Hi! @andrewjaykeller it is still showing a blank screen.
![screen shot 2018-11-23 at 7 46 44 pm](https://user-images.githubusercontent.com/17671208/48947794-68d8cf80-ef58-11e8-8272-aebc03fa10c5.png)
