### ISSUE TITLE
Indication of SW Version

### ISSUE THREAD

**Issue by jps2000** [OpenBCI/OpenBCI_GUI#407]
## Problem
Software version number is  shown during startup but only very short time
Seem to depend on start up speed / Windows version ( time is not constant???)
pls check

In a perfect world, what do you expect to happen.

display it for 0.5 - 1  second at least or show it permanently somewhere

Windows

Windows 10 seems worse than W7  or is it dependent on PC speed ???
## GUI Version
4.0.3

## Running standalone app

downloaded app 
## Type of OpenBCI Board

n/a
## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
I could easily add the version to the hover text of the "Update" button.

**Comment by andrewjaykeller** [comment]
Good idea!

**Comment by retiutut** [comment]
![screen shot 2018-11-20 at 9 14 26 am 2](https://user-images.githubusercontent.com/25914123/48782958-e8d70f00-eca4-11e8-92d8-2df19284aafb.png)

**Comment by andrewjaykeller** [comment]
!

**Comment by andrewjaykeller** [comment]
PR?

**Comment by jps2000** [comment]
solved in 4.0.1
