### ISSUE TITLE
OpenBCI GUI will not run

### ISSUE THREAD

**Issue by stemcubator** [OpenBCI/OpenBCI_GUI#409]
## Problem

OpenBCI GUI v4.0.3-beta.0 will not launch in Windows 10

## Expected 

Run the program

## Operating System and Version

Windows 10 64 bit 
Version 1803 (OS Build 17134.407)

## GUI Version

OpenBCI GUI v4.0.3-beta.0

## Running standalone app

Yes I am run the stand alon app

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by jps2000** [comment]
Had same problem on my W10 installation ( use also W7 elsewhere)  but was not sure what it caused. ( hang with gray screen during start)
Throwed then completely away old version including Hub and re-installed everything including zadig driver installation and shortcuts.
This made it work.

**Comment by jps2000** [comment]
UNfortunately now it does not work any more  so there is an issue.
Starts with light grey than turn a little bit darker and it hangs.
Can you pls list in the dark screen what the program is doing during loading to trace back where it hangs?
Is there another way to debug?
