### ISSUE TITLE
Open BCI GUI gets stuck when connecting to WifiSheild 

### ISSUE THREAD

**Issue by HamzaHummam** [OpenBCI/OpenBCI_GUI#417]
## Problem
GUI is stuck as soon as we click on Start System button
Explain the problem
We are tying to collect data from Cyton board through Wifi shield but the GUI is stuck as soon as we click on Start System button

## Expected 
GUI should display the widget screen after the Start System button is clicked

## Operating System and Version
macOS 

## GUI Version
3.3.1 , 4.0.3 , 3.3.4

## Running standalone app
We are running the standalone app

## Type of OpenBCI Board
Cyton

## Are you using a WiFi Shield?
Yes

**Comment by jupistar** [comment]
I'm having this problem, too. I get a message in the status bar saying something about default settings, but I just stare at a blue screen. Repeatedly trying Start System after selecting the WiFi shield in the menu doesn't help: the Control Panel disappears, the status message appears, and the GUI does nothing.

**Comment by retiutut** [comment]
@jupistar Try using the latest GUI that contains the ConsoleLog feature in the top right of the GUI. From there, you can now copy any errors that print. If the GUI crashes, find go to `SavedData/Settings/console-data.txt`. This feature should help solve issues in a more timely manner!

**Comment by jupistar** [comment]
Thanks for the follow-up. I’m in the middle of some other research at the moment and hope to return to this project in the next few weeks. I’ll update, then.



Josh Letterman
Systems Analyst
547 Salmon Falls Rd., Rochester, NH 03868
603.400.2121
josh.letterman@systemology.net<mailto:josh.letterman@systemology.net>
www.systemology.com
