### ISSUE TITLE
[USABILITY] Warn users when the dongle and device are not on the same channel

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#418]
## Problem

It's very confusing for new users if they hit "START SYSTEM" and then "Start Data Stream" but no data is streaming because the dongle and device are not on the same channel (or the device is off!). There is no warning or message to explain why no data is streaming, app behaves as if everything is normal.

When hitting "STATUS", the message "System is down" is pretty vague and does not convey to new users that the device and dongle are not talking at all. Users might assume they are talking, but that something else is wrong with the device.

## Expected 

- When hitting "START SYSTEM" or "Start Data Stream" (ideally both, but at least the latter) warn users that the dongle and the device are not talking (due to channel mismatch, or device being off). A good place for this would be the status bar at the bottom. 

- When hitting "STATUS", we either get "System is up" or "System is down". Replace that with something else that explains that the dongle and the device are either talking or not talking. If they're not talking, suggest the "AUTOSCAN" button.

## Operating System and Version

macOS/Windows/Linux

**Comment by retiutut** [comment]
Working on this today!

**Comment by retiutut** [comment]
![Screen Shot 2019-05-04 at 12 27 08 PM](https://user-images.githubusercontent.com/25914123/57182716-f1dd2680-6e67-11e9-97e0-19b1a96040c7.png)

**Comment by retiutut** [comment]
"Success: System is up" or "Failure: System is down" are messages received from the board. As a compromise, the GUI can display additional information as Errors or Successes as seen above.

**Comment by daniellasry** [comment]
All we need to do here is replace "system is up" and "system is down" with somethinng more descriptive. For example:

"Success: Cyton dongle and board are connected"

"Failure: Cyton dongle could not connect to the board. Perhaps they are on different channels? Try hitting AUTOSCAN"

Most users will not click "STATUS" before starting the system. They will jsut pick a serial port and click "START SYSTEM". We need a way to show these users the failure error message. What you did with the output() message seems good enough IMO!

**Comment by retiutut** [comment]
![Screen Shot 2019-05-04 at 12 43 08 PM](https://user-images.githubusercontent.com/25914123/57182870-5600ea00-6e6a-11e9-88df-3ad1f6af2d32.png)

**Comment by retiutut** [comment]
@daniellasry I can do that. I can catch both of those messages from the board and re-write them.

**Comment by retiutut** [comment]
Should be fixed, here is the case where the Cyton board is off but the user selects the Dongle

![Screen Recording 2019-05-04 at 2 47 47 PM 2019-05-04 14_49_23](https://user-images.githubusercontent.com/25914123/57184216-d0873500-6e7d-11e9-81da-698c13ad65d6.gif)

**Comment by daniellasry** [comment]
Great fix richard!

**Comment by retiutut** [comment]
![Screen Shot 2019-05-04 at 1 42 48 PM](https://user-images.githubusercontent.com/25914123/57185873-c115e500-6e99-11e9-9270-d75ca4e4e2ef.png)
