### ISSUE TITLE
Time Series Widget: Setting window to "7 sec" puts permanent blob on channels 2-7

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#419]
## Problem

In the time series widget, change the window to "7 sec".
A big blob appears at the beginning of channels 2-7. The blob stays there until you change the window time again. See pic:

![capture](https://user-images.githubusercontent.com/412426/50721029-2af9bb80-106d-11e9-8af7-79965223ec7a.PNG)

## Expected 

There should not be a blob in the background when using "7 sec" window

## Operating System and Version

Windows

## GUI Version

4.0.3

## Running standalone app

standalone

## Type of OpenBCI Board

Cyton + Wifi

## Are you using a WiFi Shield?

Yes

**Comment by retiutut** [comment]
I already fixed this. It's in the latest pull request.

https://github.com/OpenBCI/OpenBCI_GUI/issues/247

**Comment by retiutut** [comment]
@daniellasry I believe this has been fixed as of 4.1.0
