### ISSUE TITLE
Time in status line is not updated every seconds

### ISSUE THREAD

**Issue by jps2000** [OpenBCI/OpenBCI_GUI#443]
## Problem
The status line shows absolute time and relative time in seconds in playback
In playback of  longer recordings ( 20 min or so) the absolute time is not updated every second. However the relative time changes every second correctly.

## Expected 
Update  absolute time also every second

## Operating System and Version
Win

## GUI Version

4.1.0 beta

## Running standalone app

 downloaded app 

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
@jps2000 Making a 20+ minute recording now to test this...

**Comment by retiutut** [comment]
@jps2000 I have reproduced this issue!

![insta](https://user-images.githubusercontent.com/25914123/53257931-f2e81f80-3690-11e9-91fd-2805259a5651.gif)

**Comment by retiutut** [comment]
`findTimesToDisplay()` in W_TimeSeries.pde can probably be updated to use the actual timestamps that appear!

**Comment by retiutut** [comment]
I'm going to try pulling from the regular time column:
```
127, 0.00, 0.00, 0.00, 0.00, 0.000, 0.000, 0.000, 10:05:14.214, 1550851514214
0, 17.02, 14.61, 8.28, 23.24, 0.000, 0.000, 0.000, 10:05:14.227, 1550851514227
```

**Comment by retiutut** [comment]
Fixed! 🔥 💻 
![insta](https://user-images.githubusercontent.com/25914123/53260726-d3082a00-3697-11e9-98ef-2ffedf673532.gif)

@jps2000 Do you think we should show the milliseconds?

**Comment by jps2000** [comment]
Absolute time is important to trace back events with videos for example. Hence there is no need for milliseconds as long as there is no slow motion  playback . 
But when you have ms now then leave it.

@retiutut 
By the way: Do you see any chance to speed up loading/handling   of long playback files?
For example sleep studies etc need analysis of recordings  in the magnitude of hours.
Such long files can not be handled now
An "easy to realize" (nothing is easy) remedy may be  a recording scheduler to  limit length of recordings
( start new recording after x minutes)

**Comment by retiutut** [comment]
Ok leaving milliseconds in. Was able to update the elapsed time algorithm also to be very accurate.

@jps2000 Let's keep #400 by itself. The solution to that issue should resolve any problems users should have resulting from working with long playback files.

**Comment by retiutut** [comment]
@jps2000 I applied a fix to for this issue in a recent update. I think this issue can be closed.

**Comment by jps2000** [comment]
Thank you
