### ISSUE TITLE
OpenBCI_Hub 2.0.6 not initialize in the OpenBCI_GUI 4.1.0 using Processing.

### ISSUE THREAD

**Issue by wellton** [OpenBCI/OpenBCI_GUI#447]
## Problem

The OpenBCI_Hub 2.0.6 not initialize in the OpenBCI_GUI 4.1.0 using Processing.

IMPORTANT = The OpenBCI_GUI version 4.0.4 with OpenBCI_Hub 2.0.5 Works, using same procedures used in the 4.1.0

obs. I put the Hub inside folder data.

obs 2. The Hub works (third image below)

![1](https://user-images.githubusercontent.com/2234645/53359403-a3645680-3911-11e9-82de-e2a4a6a7f8cb.png)

![2](https://user-images.githubusercontent.com/2234645/53359482-c989f680-3911-11e9-8fcf-771d9a36ceef.png)

![2](https://user-images.githubusercontent.com/2234645/53359642-3e5d3080-3912-11e9-9c87-6bbf1755c35a.png)

## Expected 

Do initialize the Hub.

## Operating System and Version

Debian GNU/Linux Buster

## GUI Version

4.1.0

## Running standalone app

Running from Processing 3

## Type of OpenBCI Board

Cyton+Daisy

## Are you using a WiFi Shield?

Yes

**Comment by retiutut** [comment]
This is likely only happening on Linux.

**Comment by daniellasry** [comment]
Ah. I believe this is due to a change I made. As of 4.1.0, you need to put the hub inside a "OpenBCIHub" folder within the "data" folder. Let us know if that fixes the issue.

**Comment by wellton** [comment]
@daniellasry Hi Daniel. Yes. Its Works. =) Thank you.

![1](https://user-images.githubusercontent.com/2234645/53403469-7ad07100-3992-11e9-906f-a27e48f82638.png)

![2](https://user-images.githubusercontent.com/2234645/53403471-7b690780-3992-11e9-8ca8-45ba1c281a27.png)

![2](https://user-images.githubusercontent.com/2234645/53403522-989dd600-3992-11e9-8259-e32ab7b9d020.png)

**Comment by pranavsuresh7** [comment]
Hey I also face the same problem mine ubuntu version is 18.04.
![screenshot from 2019-02-28 19-25-34](https://user-images.githubusercontent.com/26823870/53571340-ad46bd80-3b8e-11e9-8416-4afc07b3185b.png)
![screenshot from 2019-02-28 19-02-41](https://user-images.githubusercontent.com/26823870/53571372-bdf73380-3b8e-11e9-8c29-f66f45ee4f08.png)

**Comment by pranavsuresh7** [comment]
Fixed it  by   sudo apt install libgconf-2-4 ,installing this library and sudo reboot. It was issue with OpenBCI_HUB

**Comment by retiutut** [comment]
@pranavsuresh7 You are using an older version of the GUI. Please try [the latest release](https://github.com/OpenBCI/OpenBCI_GUI/releases/latest)
