### ISSUE TITLE
Can't clear wifi certifications

### ISSUE THREAD

**Issue by Gingerlief** [OpenBCI/OpenBCI_GUI#450]
## Problem
So the wifi module cannot be seen via WiFi direct anymore and cannot access it via the network as well being the schools public server. Is there a means to do a hardware reset of the wifi credentials?

## Are you using a WiFi Shield?

Yes

**Comment by retiutut** [comment]
http://docs.openbci.com/Tutorials/03-Wifi_Getting_Started_Guide#wifi-getting-started-guide-wifi-configuration-for-firmware-20-and-later-erase-stored-credentials

This is not a problem with the GUI, please close this issue.
