### ISSUE TITLE
Add support to prevent long recordings

### ISSUE THREAD

**Issue by jps2000** [OpenBCI/OpenBCI_GUI#461]
## Problem

Playback or handling long recordings is a problem due to file size. However, sleep studies require long recording and it is laborious  and erroneous to start and stop recordings  every 20-30 minutes.

## Expected 
There could be a recording scheduler to  start a new file every xx minutes
in the Pick Transfer Protocol box there is the DATA LOG FILE section where a file name can be entered. There may be added a line  Log time limit    (no, 10, 20, 40, 60 minutes)
Data logging should end after this time and restarted asap with a new file name.
This prevents  from getting  too long recordings and makes the system more robust for data loss.

Consider also to start / stop data logging with a separate button.
Use case is to start data stream. Then you check impedance, electrodes, signals etc.  
Now  data logging is  already running  unnecessarily.
After everything is ready data logging should start - or not(yet)! whatever the user likes

## Operating System and Version

W

## GUI Version

all

## Running standalone app

downloaded app 

## Type of OpenBCI Board

Cyton/Cyton+Daisy/Ganglion

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
@jps2000 Thank you for making this issue! It is on the to-do list!

**Comment by retiutut** [comment]
@jps2000 Check out https://github.com/OpenBCI/OpenBCI_GUI/issues/483 ! This should work!

**Comment by retiutut** [comment]
https://openbci.com/index.php/forum/#/discussion/1668/unable-to-convert-large-files-from-sd-card-out-of-memory-error

**Comment by jps2000** [comment]
Thank you
But still:  splitting long events into digestable pieces is a good one. It also prevents inherently (huge) data loss.

**Comment by retiutut** [comment]
![Screen Shot 2019-06-21 at 2 44 34 PM](https://user-images.githubusercontent.com/25914123/59955322-1e1c2900-944f-11e9-8ddf-024ecd957b5a.png)

**Comment by retiutut** [comment]
![Screen Shot 2019-06-21 at 8 34 49 PM](https://user-images.githubusercontent.com/25914123/59957919-15821d80-9464-11e9-97b9-a4111475477c.png)

**Comment by jps2000** [comment]
Looks great
thank you. 
Small comments: call it Max file  duration or length instead of size 
length:
infinite, 5, 15, 30, 60,120 as length
just to get it right:
after time over a new recording is started and ends again after preset minutes.

**Comment by retiutut** [comment]
I'm **not** going to put a "No Limit" or "Infinite" option, as this defeats the point of this fix.

I **can** change the options to 5,15,30,60,90,120.

**Comment by retiutut** [comment]
I've changed my mind. Let's do:

5, 15, 30, 60, 120, No Limit

**Comment by retiutut** [comment]
![Screen Shot 2019-06-22 at 3 20 50 PM](https://user-images.githubusercontent.com/25914123/59968578-54b27c00-9501-11e9-87e1-f79837fd8514.png)

**Comment by retiutut** [comment]
Super excited to share this next picture!!! Zero data loss using nanoTime()!!! Files set to 1 min max length produce files of exact same size.
![Uploading Screen Shot 2019-06-22 at 4.55.23 PM.png…]()

**Comment by retiutut** [comment]
Done 🔥 🔥 🔥 
![Screen Shot 2019-06-22 at 5 35 24 PM](https://user-images.githubusercontent.com/25914123/59969507-1ffbf000-9514-11e9-8c9c-9ba0f948cfb8.png)
