### ISSUE TITLE
Improve band power widget

### ISSUE THREAD

**Issue by jps2000** [OpenBCI/OpenBCI_GUI#462]
## Problem
The chart would look better if the bars are colored  
blue, magenta, green, yellow red  (left to right)
The response time goes with smooth of the FFT plot ??
## Expected 

Color the bars blue, magenta, green, yellow red  (left to right)
Provide dedicated smoothing adjustment independent of FFT

## Operating System and Version

w

## GUI Version
all

## Running standalone app

app

## Type of OpenBCI Board

Cyton/Cyton+Daisy/Ganglion

## Are you using a WiFi Shield?

n

**Comment by retiutut** [comment]
@jps2000 Adding this issue to the to-do list also!

**Comment by retiutut** [comment]
![Screen Shot 2019-05-03 at 7 59 17 PM](https://user-images.githubusercontent.com/25914123/57171828-f0ffb280-6ddd-11e9-89d4-6f321ee7dcca.png)

**Comment by jps2000** [comment]
thank you
