### ISSUE TITLE
problem to run openbci cyton

### ISSUE THREAD

**Issue by babilord** [OpenBCI/OpenBCI_GUI#481]
## Problem

hi, i have been using cyton openbci since 2 years. everything was good and openbci code worked perfectly, but 2 days I can't work with openbci, because when I click on start then I see this error : java.lang.pointerException. I don't changed my code!! what happen?! please help me, thank u...

## Expected 

In a perfect world, what do you expect to happen.

## Operating System and Version

Windows

## GUI Version

processing 2.2.1

## Running standalone app
processing 2.2.1

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
What version of the OpenBCI_GUI are you using?

**Comment by babilord** [comment]
I don't know :| how can I understand it?

**Comment by daniellasry** [comment]
What do you see here?

![Untitled](https://user-images.githubusercontent.com/412426/56139255-600b8900-5f4d-11e9-9be8-3647f249ba79.png)
