### ISSUE TITLE
Organize recording sessions in their own timestamped folder

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#483]
Proposal for new folder structure:
```
OpenBCI_GUI/
|---- Sample_Data/
|---- Settings/
|---- Console_Data/
|---- Recordings/
      |---- OpenBCI-BDF-2019-06-21_21-31-24.bdf
      |---- OpenBCISession_2019-04-14_20-40-48/
            |---- ~~console-data.txt~~Put In Console_Data Folder Instead
            |---- OpenBCI-RAW-2019-04-14_20-40-48.txt
            |---- OpenBCI-RAW-2019-04-14_20-45-32.txt
            |---- OpenBCI-RAW-2019-04-14_20-56-08.txt
            |---- OpenBCI-RAW-2019-04-14_21-03-23.txt
      |---- OpenBCISession_2019-04-15_09-40-48/
            |---- ~~console-data.txt~~
            |---- OpenBCI-RAW-2019-04-15_09-40-48.txt
            |---- OpenBCI-RAW-2019-04-15_09-44-21.txt
            |---- OpenBCI-RAW-2019-04-15_09-59-03.txt
            |---- OpenBCI-RAW-2019-04-15_10-11-43.txt
      |---- etc...
            |---- etc...
            |---- etc...
      |---- etc...
            |---- etc...
            |---- etc...
```

Retiutut: Updated to reflect console data in its own folder and require BDF files in Recordings Folder

**Comment by retiutut** [comment]
This includes moving console-data.txt from SavedData/Settings/ to SavedData.

**Comment by retiutut** [comment]
Above proposed solution Fixes #461 🔥

**Comment by retiutut** [comment]
Requirement: Change name of “Saved File” to “Saved Session”

**Comment by retiutut** [comment]
Requirement: create `Documents/OpenBCI_GU/Sample_DataI` and copy sample data on first launch, or if the files don't exist

**Comment by retiutut** [comment]
Requirement: Console Data will have to be in its own folder, because this describes activity from App Start to App Stop, as opposed to Session Start/Stop

**Comment by retiutut** [comment]
C'est très bon!
![Screen Shot 2019-06-21 at 9 32 09 PM](https://user-images.githubusercontent.com/25914123/59958420-1919a280-946c-11e9-9e8d-c62394a67fc3.png)

**Comment by retiutut** [comment]
Done 🔥 🔥 🔥 
![Screen Shot 2019-06-21 at 10 23 20 PM](https://user-images.githubusercontent.com/25914123/59958881-40c03900-9473-11e9-8363-e3f20c6856bb.png)

**Comment by daniellasry** [comment]
Nailed it!
