### ISSUE TITLE
GUI Freeze when selecting playback

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#487]
## Problem

I select the playback widget and click the "SELECT PLAYBACK FILE" and the GUI freezes

## Expected 

I want the GUI to open a new file for playback without freezing.

## Operating System and Version

macOS

## GUI Version

4.0.3

## Running standalone app

Are you running the downloaded app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by daniellasry** [comment]
Thanks for opening this one. The latest version of macOS mojave 10.14.4 is causing processing sketches to crash when they open any new window. This includes the file selection window. Works fine in 10.14.3.

There's an open issue on the processing github: https://github.com/processing/processing/issues/5836

We're still looking for a workaround.
