### ISSUE TITLE
Playback files with long names overflow the playback history menu

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#490]
![image](https://user-images.githubusercontent.com/412426/56371180-787bdd80-61b1-11e9-81af-e7d7e77d8ba2.png)

Possible solution: truncate the string after a certain amount of characters and append "..." to the end.

Perhaps even better: Show the beginning and end of the string, and put a [...] in the middle

**Comment by retiutut** [comment]
![Screen Shot 2019-04-20 at 2 49 13 PM](https://user-images.githubusercontent.com/25914123/56461615-82513c80-637b-11e9-9df2-94c38bb2e895.png)

**Comment by daniellasry** [comment]
That looks perfect!

**Comment by retiutut** [comment]
Should we store the truncated name in the JSON under id? or make a new key?

**Comment by retiutut** [comment]
Still needs more work.
