### ISSUE TITLE
Unstable Digital read on version 4.1.2(beta)

### ISSUE THREAD

**Issue by lopezvaa** [OpenBCI/OpenBCI_GUI#506]
## Problem

I am attempting to set up an external trigger through my cyton board. However, when switching on the digital read via the GUI, I am getting seemingly random numbers from D11, 12, 13, 17,18. (D18 hovers around 8000 and seems to be an accelerometer).  Pushing the prog button should turn D17 from 0 to 1; however, it presents random numbers.

![DigitalReadError2](https://user-images.githubusercontent.com/30287962/57124809-71df8f80-6d87-11e9-9f36-8d9bc0bc5950.PNG)

The Raw output files does not record the digital channesl instead, it is as if the accelerometer data was being sampled.

![DigitalReadError3](https://user-images.githubusercontent.com/30287962/57124816-773cda00-6d87-11e9-9a12-648daead841c.PNG)

## Expected 

I expected to see the Digital reads as 0s and 1s and see a state change with a TTL level change (or pressing the prog button) and the raw files to contain the 5 columns for the digital inputs rather than the three accelerometer ones.

## Operating System and Version
Windows 10 Enterprise 64 bi

## GUI Version

4.1.2 (beta)

## Running standalone app

Standalone app

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by lopezvaa** [comment]
I ran the GUI code in Processing. There, the digital read functionallity works fine and the raw file outputs the digital channels as it is meant to. So, the issue is narrowed down to the stand alone release v4.1.2 (beta) that I downloaded while trying to get my wifishield to work,

Rolling back to release 4.0.4 fixed it (the latest stable release from the Download section is 4.0.03 also works)

Kind regards
Alejandro

**Comment by retiutut** [comment]
@lopezvaa Thanks for the screenshots, looking into this soon.

**Comment by retiutut** [comment]
I don't think the GUI code has changed. Possibly Hub related.

**Comment by retiutut** [comment]
At least the older version works, so there is a standard of what should be happening. I can see that the current values in 4.1.2 are indeed accelerometer data instead of digital read.

**Comment by retiutut** [comment]
I might have found the problem. Maybe digital read is turned on in the GUI but the wrong code is sent to the board.

**Comment by retiutut** [comment]
Fixed 🔥 
![2019-05-05 11-44-30 2019-05-05 11_46_28](https://user-images.githubusercontent.com/25914123/57197339-b1df7780-6f2b-11e9-8339-833f9f40d678.gif)

**Comment by lopezvaa** [comment]
Great @retiutut ! thanks for the updates and the prompt response. Should I close the Issue or do you do that yourself?

**Comment by retiutut** [comment]
I'll close the issue when the Pull Request is done.
