### ISSUE TITLE
Match Time Series drop-down behavior to other graphs

### ISSUE THREAD

**Issue by sublimatedpotato** [OpenBCI/OpenBCI_GUI#509]
## Problem

The drop-down menus in Time Series widget do not close or allow alternate selection after making a selection. The drop-down must be closed and re-opened to make an additional selection.

<img width="709" alt="Screen Shot 2019-05-05 at 2 48 55 PM" src="https://user-images.githubusercontent.com/37374466/57198852-d7797a80-6f45-11e9-8cf9-fdae6952fc5d.png">

## Expected 

All other drop-downs for the other widgets appear to auto-close after a selection is made, so this is the expected behavior in Time Series, too.

## Operating System and Version

macOS

## GUI Version

4.1.2-beta.0

## Running standalone app

No

## Type of OpenBCI Board

None

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
Thanks for catching this! Enforcing the style and functionality already in place!

**Comment by sublimatedpotato** [comment]
No problem @retiutut . Thanks for getting it resolved! Had just opened the app for the first time to explore #315 and #180 and noticed this. Figured it could be an easy solution. Hoping to get more involved on the repo in general, though.
