### ISSUE TITLE
Old Cyton

### ISSUE THREAD

**Issue by MB0105** [OpenBCI/OpenBCI_GUI#513]
## Problem

I bought a Cyton board in 2015, but haven't used it until now. I tried communicating with the new Open BCI GUI (v4.0.3), and I get a 'connection time out' when attempting to communicate via the serial port and the dongle. Do I need to update any firmware on the board or dongle? which one and how do I do that?

## Expected 

Cyton board will communicate with computer

## Operating System and Version

Windows 10

## GUI Version

v4.0.3

## Running standalone app

Are you running the downloaded app or are you running from Processing 3
downloaded up 
## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
I'm still using Cyton Firmware 3.1.1, but 3.1.2 is available.

https://docs.openbci.com/Hardware/05-Cyton_Board_Programming_Tutorial

- First, "Install Firmware From Arduino Library Manager"
- Then, follow the instructions carefully to upload the new firmware (currently 3.1.2) via the dongle

I would make sure there isn't any metal or objects near the dongle and Cyton that would cause signal interference. 

Also, the latest GUI 4.1.2 will be done with beta testing soon.
