### ISSUE TITLE
Add Accelerometer/AuxData to Networking Widget

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#532]
## Problem

Users might want to stream Accelerometer data using any networking protocol...

Cyton users might want to stream Aux data when analog read or digital read are turned turned on...

## Expected 

Stream Accelerometer data from Ganglion and Cyton using Serial/UDP/LSL/OSC.

Stream Aux Data from Cyton using the same method.

Add a datatype named Accel, that adapts to Accel/Aux for Cyton mode.

Each protocol should be tested using 3rd party software/hardware:
- Serial: Arduino ✅
- LSL: OpenVibe
- UDP: Max/MSP
- OSC: Max/MSP

## Operating System and Version

all OS

## GUI Version

4.1.2

## Running standalone app

both

## Type of OpenBCI Board

all boards

## Are you using a WiFi Shield?

maybe

## Console Log

no output to display

**Comment by jps2000** [comment]
good point
Cyton is reference for axis orientation
You may also add aux channels as well
