### ISSUE TITLE
Widget: Data Logging History

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#55]
A widget that pops up when the data log bar is clicked on showing that last 100 entries.

**Comment by retiutut** [comment]
@daniellasry The solution I came up with for this was the Playback widget. During playback mode, user can select from up to 100 previously loaded playback files. The widget isn't perfect, but it does work as expected. Implemented as of GUI v4.0.0

**Comment by daniellasry** [comment]
Agreed, the playback widget takes care of this.
