### ISSUE TITLE
Unable to establish link to Hub 

### ISSUE THREAD

**Issue by DanielHHowell** [OpenBCI/OpenBCI_GUI#553]
## Problem

Receiving the error "Unable to establish link to Hub. Live functionality will be disabled". 

I've determined the issue to be with the hub itself, when I try to run it I receive the error "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found", however the most up to date version of libc for Ubuntu 18.04 LTS is 2.27, and upgrading past that could break things if I understand correctly. So why is the Hub requiring a version of libc not supported on the current Ubuntu LTS? I am not confident this is actually an issue with the OpenBCIHub as it is my system but not sure where else to turn. Thanks in advance!

## Expected 

Hub connection!

## Operating System and Version

Linux (Ubuntu 18)

## GUI Version

4.1.2.

## Running standalone app

Processing

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

## Console Log

[ERROR] "Unable to establish link to Hub. Live functionality will be disabled"

**Comment by retiutut** [comment]
Sorry, but you've contradicted yourself.

> I've determined the issue to be with the hub itself

> I am not confident this is actually an issue with the OpenBCIHub as it is my system but not sure where else to turn

I can try to look into this...

**Comment by retiutut** [comment]
"Unable to establish link to Hub. Live functionality will be disabled"  -- appears when the Hub takes too long to load or fails to launch

**Comment by retiutut** [comment]
Not able to replicate this issue... probably an issue with your system.

**Comment by retiutut** [comment]
If you really want to, you could try running the OpenBCIHub directly from Visual Studio Code. Just tested Hub 2.0.8 (again). No errors.

**Comment by retiutut** [comment]
https://askubuntu.com/questions/421642/libc-so-6-version-glibc-2-14-not-found

**Comment by retiutut** [comment]
Furthermore, searching the Hub code shows that "glib" is not mentioned in code or dependencies.

**Comment by retiutut** [comment]
https://www.linode.com/docs/security/security-patches/patching-glibc-for-the-ghost-vulnerability/

**Comment by DanielHHowell** [comment]
I appreciate all the help! Yes the standalone works fine, it's only when launching the hub in attempt to run the processing IDE. Have now tried this on 3 separate Ubuntu machines and receiving the same error - libc6 is up to date at 2.27 but it is requesting 2.28. Thanks for the assistance in any case

**Comment by DanielHHowell** [comment]
"Having downloaded and extracted the binary release, one of the modules it uses indeed seems to have a GLIBC_2.28 symbol:

$ mkdir app
$ asar e resources/app.asar app
$ grep -r GLIBC_2.28
Binary file app/node_modules/serialport/build/Release/obj.target/serialport.node matches
Binary file app/node_modules/serialport/build/Release/serialport.node matches
Binary file app/node_modules/@serialport/bindings/build/Release/obj.target/bindings.node matches
Binary file app/node_modules/@serialport/bindings/build/Release/bindings.node matches
Binary file resources/app.asar matches"

**Comment by retiutut** [comment]
That's cool, but you are talking about another package, and in the binaries.

**Comment by retiutut** [comment]
I would recommend finding a way to make sure the Hub can launch directly from Visual Studio Code.

**Comment by DanielHHowell** [comment]
Got it - will give that a shot, thank you.

**Comment by retiutut** [comment]
@DanielHHowell I have reproduced the error. It's a problem with the 2.0.9 build that is currently posted. When I built the Hub again, it works fine.

To fix this, we are going to upload a new 2.0.9 version of the hub with no changes.

Thank you for being patient. Take care!

**Comment by retiutut** [comment]
The following error occurs using the current, and soon to be replaced, 2.0.9 Hub for Linux only:
![IMG_8233](https://user-images.githubusercontent.com/25914123/61070165-984b2800-a3d3-11e9-986f-ce5fdabbe249.png)

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_Hub/issues/99

**Comment by retiutut** [comment]
Getting fixed today or tomorrow. Also, release 4.1.3-beta.2 is happening today/tomorrow.

**Comment by retiutut** [comment]
This should work for you!

https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v4.1.3-beta.2
