### ISSUE TITLE
error when opening openBCIHUB on GUI v4.1.2

### ISSUE THREAD

**Issue by masgani** [OpenBCI/OpenBCI_GUI#562]
## Problem

Displayed error when running the GUI, it is known that it came from OpenBCIHub.exe

## Expected 

The GUI runs and Hub is connected.

## Operating System and Version

Windows 10

## GUI Version

4.1.2

## Running standalone app

Downloaded app

## Type of OpenBCI Board

Cyton+Daisy

## Are you using a WiFi Shield?

No

## Console Log

![errorBCI](https://user-images.githubusercontent.com/15261171/61368159-7a8c3000-a8b7-11e9-8016-d6d499e2fbdf.JPG)

**Comment by retiutut** [comment]
Please use 4.1.3-beta.3 or newer.
