### ISSUE TITLE
BandPower visualization widget does not work

### ISSUE THREAD

**Issue by Otemo** [OpenBCI/OpenBCI_GUI#573]
## Problem
BandPower visualization widget could not be displayed in OpenBCI GUI.
When BandPower was choosed, GUI freezed.

## Expected 
BandPower can be choosed from a pull-down menu, then visualizaed.

## Operating System and Version
Windows10

## GUI Version
v4.1.4-beta.0
OpenBCIHub v2.0.9

## Running standalone app
running from Processing

## Type of OpenBCI Board
Ganglion

## Are you using a WiFi Shield?
No

![PowerBand](https://user-images.githubusercontent.com/38579786/62906442-a8c33980-bda9-11e9-91bc-44deea337147.gif)

**Comment by retiutut** [comment]
@Otemo I have replicated this issue using Synthetic (4 Channels)! Should be able to fix this quickly. Thank you for testing the latest release!!!

**Comment by retiutut** [comment]
![Screen Shot 2019-08-13 at 10 22 59 AM](https://user-images.githubusercontent.com/25914123/62954054-54718700-bdb4-11e9-820c-d328893da13c.png)

**Comment by retiutut** [comment]
This issue is being caused by the new ChannelSelect dropdown in the BandPower widget.

**Comment by Otemo** [comment]
Hi retiutut,
Thank you for your quick support. I have confirmed that the GUI works properly!
