### ISSUE TITLE
Widget: SSVEP

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_GUI#59]

**Comment by retiutut** [comment]
SSVEP has been merged to development, still needs testing/editing as needed to achieve desired results.

**Comment by retiutut** [comment]
Note: Data processing for SSVEP widget was derived using the following deprecated code - https://github.com/jnaulty/OpenBCI_Processing/blob/ssvep-neurogaming/OpenBCI_GUI/EEG_Processing.pde
