### ISSUE TITLE
Networking Widget Start/Stop button broken

### ISSUE THREAD

**Issue by lopezvaa** [OpenBCI/OpenBCI_GUI#593]
## Problem

When starting data streams through the Networking Widget after pressing the start button on the streamer, the data stream starts as expected, the button then turns into a red 'STOP' button but the stream does not stop. 

This causes the widget to get stuck on its current configuration and in order to change the streams, the session has to be stopped. However this causes the GUI to crash and fails to start a new session.

## Expected 

I would expect the streams to stop when the 'STOP' button is pressed and the widget can be modified and started again. If there is only one networking chance per session then the widget should not crash the GUI after the session has been stopped

![image](https://user-images.githubusercontent.com/30287962/64691717-ad0b7100-d493-11e9-8774-d6c9ae948b8f.png)

## Operating System and Version

Windows 10, 64-bit

## GUI Version

4.1.5 beta 3

## Running standalone app

Both stand alone and processing are faulty

## Type of OpenBCI Board

Cyton

## Are you using a WiFi Shield?

No

## Console Log

Console Log Started at Local Time: 2019-09-11_12-52-47
Screen Resolution: 1920 X 1080
Welcome to the Processing-based OpenBCI GUI!
For more information, please visit: https://openbci.github.io/Documentation/docs/06Software/01-OpenBCISoftware/GUIDocs
Launching application from local data dir
OpenBCI_GUI: hubStart: OS Detected: Windows
Local Version: 415, Latest Version: 415
GUI is up to date!
OpenBCI_GUI::Setup: Is RX mulitcast: false
OpenBCI_GUI::Setup: Has RX joined multicast: false
OpenBCI_GUI::Setup: Sample Data exists in Documents folder.
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
The file "C:\Users\aova\Documents\OpenBCI_GUI\Settings\UserPlaybackHistory.json" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
OpenBCI_GUI::Control Panel: Playback history file not found or other error.
OpenBCI_GUI::Setup: Setup is complete!
Instantiating hub object...
Hub: CheckHubInit: The GUI is connected to the Hub!
sourceList: click! 
setInterface: curInterface: -1
channel count set to 8
Setting Latency to 10000
Setting WiFi Internet Protocol to tcp
Setting WiFi style to dynamic
[DEFAULT]: Protocol Serial Selected for Cyton
setInterface: curInterface: 0
Setting sample rate for Cyton to 250Hz

sample rate set to: 250
[DEFAULT]: Transfer Protocol set to serial
serialList: click! 
[DEFAULT]: OpenBCI Port Name = COM10
Settings: LogFileMaxDuration = 60 minutes
Calling initSystem()

=================================================
||             INITIALIZING SYSTEM             ||
=================================================

InitSettings: Saving Default Settings to file!
SoftwareSettings: 3 active widgets saved!
LoadGUISettings: Applied Widget 0 to Container 4
LoadGUISettings: Applied Widget 2 to Container 9
Networking Data Types || show num dropdowns = 6
LoadGUISettings: Applied Widget 3 to Container 3
Hub: sendCommand(String): sending '/0'
Cyton: setBoardMode to :DEFAULT
LoadGUISettings: Expert Mode Off
Hub: processCommand: success -- 42504
Hub: processConnect: made it -- 42595 code: 200
Hub: setBoardType(): sending 'cyton -- 42595
Hub: processBoardType: success -- 42597
[SUCCESS]: The GUI is done initializing. Settings Loaded! Press "Start Data Stream" to start streaming! --  Cyton firmware v3.1.2
Networking: Protocol mode set to LSL
Networking Data Types || show num dropdowns = 6
Apply LSL Networking Mode
Ch 0, Active, x24, Normal, Include, On, Off
Ch 1, Active, x24, Normal, Include, On, Off
Ch 2, Active, x24, Normal, Include, On, Off
Ch 3, Active, x24, Normal, Include, On, Off
Ch 4, Active, x24, Normal, Include, On, Off
Ch 5, Active, x24, Normal, Include, On, Off
Ch 6, Active, x24, Normal, Include, On, Off
Ch 7, Active, x24, Normal, Include, On, Off
Success writing channel 0
Return code: 200
Success writing channel 1
Return code: 200
Success writing channel 2
Return code: 200
Success writing channel 3
Return code: 200
Success writing channel 4
Return code: 200
Success writing channel 5
Return code: 200
Success writing channel 6
Return code: 200
Success writing channel 7
OpenBCI_GUI: setup: RESIZED
Networking Data Types || show num dropdowns = 10
Pulse Sensor Widget -- Screen Resized.
dy = 0
Acc Widget -- Screen Resized.
WidgetManager.pde: Remapping widgets to container layout...
headPlot: computeWeightFactor: Ielec 0, solution complete with 2000 iterations. max_dVal = 3.33786E-5
headPlot: computeWeightFactor: Ielec 1, solution complete with 2000 iterations. max_dVal = 3.334284E-5
headPlot: computeWeightFactor: Ielec 2, solution complete with 2000 iterations. max_dVal = 5.825758E-5
headPlot: computeWeightFactor: Ielec 3, solution complete with 2000 iterations. max_dVal = 5.786419E-5
headPlot: computeWeightFactor: Ielec 4, solution complete with 2000 iterations. max_dVal = 2.0375848E-5
headPlot: computeWeightFactor: Ielec 5, solution complete with 2000 iterations. max_dVal = 2.0226837E-5
[DEFAULT]: Data stream started.
Cyton: startDataTransfer(): writing 'b' to the serial port...
Hub: sendCommand(char): sending 'b'
OpenBCI_GUI: openNewLogFile: opened ODF output file: C:\Users\aova\Documents\OpenBCI_GUI\Recordings\OpenBCISession_2019-09-11_12-52-51\OpenBCI-RAW-2019-09-11_12-54-07.txt
Hub: processCommand: success -- 83396
Stream update numChan to 8
nPointsPerUpdate 10
dataToSend len: 80
Stream update numChan to 8
nPointsPerUpdate 10
dataToSend len: 80
Stream update numChan to 8
nPointsPerUpdate 10
dataToSend len: 80
Networking: StringList size=5 [ "TimeSeries", "obci_eeg1", "EEG", "8", "1" ]
Networking: StringList size=5 [ "BandPower", "obci_eeg2", "EEGbp", "8", "1" ]
Networking: StringList size=5 [ "FFT", "obci_eeg3", "EEGfft", "8", "1" ]
[DEFAULT]: Network Stream Started
Hub: apparent sampleIndex jump from Serial data: 154 to  156.  Keeping packet. (1)
numPacketsDropped = 1
Hub: apparent sampleIndex jump from Serial data: 214 to  216.  Keeping packet. (2)
numPacketsDropped = 1
Hub: apparent sampleIndex jump from Serial data: 179 to  181.  Keeping packet. (3)
numPacketsDropped = 1
[DEFAULT]: Data stream stopped.
Cyton: startDataTransfer(): writing 's' to the serial port...
Hub: sendCommand(char): sending 's'
Hub: processCommand: success -- 169554
OpenBCI_GUI: mousePressed: clicked in CP box
OpenBCI_GUI: mousePressed: clicked in CP box
[INFO]: Learn how to use this application and more at openbci.github.io/Documentation/
openBCI_GUI: haltSystem: Halting system for reconfiguration of settings...
openBCI_GUI: haltSystem: Network streams stopped
Cyton: startDataTransfer(): writing 's' to the serial port...
Hub: sendCommand(char): sending 's'
SoftwareSettings: 3 active widgets saved!
Hub: processCommand: success -- 178777
Closing any open SD file. Writing 'j' to OpenBCI.
Hub: sendCommand(char): sending 'j'
Hub: processCommand: success -- 178802
Disconnecting serial...
The file "C:\Users\aova\Documents\OpenBCI_GUI\Settings\UserPlaybackHistory.json" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
OpenBCI_GUI::Control Panel: Playback history file not found or other error.
serialList: click! 
[DEFAULT]: OpenBCI Port Name = COM10
Settings: LogFileMaxDuration = 60 minutes
Calling initSystem()

=================================================
||             INITIALIZING SYSTEM             ||
=================================================

headPlot: computeWeightFactor: Ielec 0, solution complete with 2000 iterations. max_dVal = 3.33786E-5
headPlot: computeWeightFactor: Ielec 1, solution complete with 2000 iterations. max_dVal = 3.334284E-5
headPlot: computeWeightFactor: Ielec 2, solution complete with 2000 iterations. max_dVal = 5.825758E-5
InitSettings: Saving Default Settings to file!
SoftwareSettings: 3 active widgets saved!
LoadGUISettings: Applied Widget 0 to Container 4
LoadGUISettings: Applied Widget 2 to Container 9
Networking Data Types || show num dropdowns = 10
LoadGUISettings: Applied Widget 3 to Container 3
Hub: sendCommand(String): sending '/0'
Cyton: setBoardMode to :DEFAULT
LoadGUISettings: Expert Mode Off
Hub: processCommand: success -- 199788
Hub: processConnect: made it -- 199878 code: 200
Hub: setBoardType(): sending 'cyton -- 199879
Hub: processBoardType: success -- 199879
[SUCCESS]: The GUI is done initializing. Settings Loaded! Press "Start Data Stream" to start streaming! --  Cyton firmware v3.1.2
headPlot: computeWeightFactor: Ielec 3, solution complete with 2000 iterations. max_dVal = 5.786419E-5
headPlot: computeWeightFactor: Ielec 0, solution complete with 2000 iterations. max_dVal = 3.33786E-5
headPlot: computeWeightFactor: Ielec 4, solution complete with 2000 iterations. max_dVal = 2.0375848E-5
headPlot: computeWeightFactor: Ielec 1, solution complete with 2000 iterations. max_dVal = 3.334284E-5
headPlot: computeWeightFactor: Ielec 5, solution complete with 2000 iterations. max_dVal = 2.0226837E-5
headPlot: computeWeightFactor: Ielec 2, solution complete with 2000 iterations. max_dVal = 5.825758E-5
headPlot: computeWeightFactor: Ielec 3, solution complete with 2000 iterations. max_dVal = 5.786419E-5
headPlot: computeWeightFactor: Ielec 4, solution complete with 2000 iterations. max_dVal = 2.0375848E-5
headPlot: computeWeightFactor: Ielec 5, solution complete with 2000 iterations. max_dVal = 2.0226837E-5
Networking: Protocol mode set to LSL
Networking Data Types || show num dropdowns = 10
Apply LSL Networking Mode
Ch 0, Active, x24, Normal, Include, On, Off
Ch 1, Active, x24, Normal, Include, On, Off
Ch 2, Active, x24, Normal, Include, On, Off
Ch 3, Active, x24, Normal, Include, On, Off
Ch 4, Active, x24, Normal, Include, On, Off
Ch 5, Active, x24, Normal, Include, On, Off
Ch 6, Active, x24, Normal, Include, On, Off
Ch 7, Active, x24, Normal, Include, On, Off
Return code: 200
Success writing channel 0
Return code: 200
Success writing channel 1
Return code: 200
Success writing channel 2
Return code: 200
Success writing channel 3
Return code: 200
Success writing channel 4
Return code: 200
Success writing channel 5
Return code: 200
Success writing channel 6
Return code: 200
Success writing channel 7
java.lang.RuntimeException: Waited 5000ms for: <25f020db, 2b37da15>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1-FPSAWTAnimator#00-Timer2>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1-FPSAWTAnimator#00-Timer2-FPSAWTAnimator#00-Timer3>
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:410)
	at java.lang.Thread.run(Thread.java:748)
RuntimeException: Waited 5000ms for: <25f020db, 2b37da15>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1-FPSAWTAnimator#00-Timer2>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1-FPSAWTAnimator#00-Timer2-FPSAWTAnimator#00-Timer3>

**Comment by retiutut** [comment]
Really had to rename this because the stop/start button is in fact working. Not surprised if LSL has bugs because it was completely non-functional for a very long time.

We are only finding these bugs out now because LSL is working.

**Comment by retiutut** [comment]
I can see now that the Start/Stop button is broken in the networking widget.

**Comment by retiutut** [comment]
The code for stopping the networking stream got removed accidentally when adding another button. Easy fix. 
https://github.com/OpenBCI/OpenBCI_GUI/commit/bc0e085b28fe1bbe433de76fa26fd7878f96c365#diff-32370e0f7a6c1e0b4ea80be34d4d7473
