### ISSUE TITLE
 No library found for com.sun.jna 

### ISSUE THREAD

**Issue by shama992** [OpenBCI/OpenBCI_GUI#609]
running open bci gui code in processing me facing this issue No library found for com.sun.jna please guide me how to run gui code properly and how to install this library and how to reslove this error fftBuff cannot be resolved to a variable

**Comment by retiutut** [comment]
Why didn't you use the Issue template???

This issue is already resolved.

**Comment by retiutut** [comment]
Try reading the instructions before assuming something is broken.

https://docs.openbci.com/docs/06Software/01-OpenBCISoftware/GUIDocs#running-the-openbci-gui-from-the-processing-ide

**Comment by shama992** [comment]
Thankyou so much sir

**Comment by shama992** [comment]
sir can i make this gui in python any reference in this way ?
