### ISSUE TITLE
BandPower visualization widget does not work in v4.1.7-beta.0

### ISSUE THREAD

**Issue by Otemo** [OpenBCI/OpenBCI_GUI#634]
## Problem
BandPower visualization widget could not be displayed

## Expected 

BandPower can be choosed from a pull-down menu and visualizaed.

## Operating System and Version

Windows10

## GUI Version

v4.1.7-beta.0
OpenBCIHub v2.1.0

## Running standalone app

running from Processing

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
There is no issue. You need to select the Channels from the ChannelSelector. 

To resolve this issue, I can make sure all channels are on by default for Ganglion.

![Screen Shot 2019-11-07 at 10 58 59 AM](https://user-images.githubusercontent.com/25914123/68410185-f1428700-014d-11ea-9def-96a6112e8429.png)

**Comment by retiutut** [comment]
I found the error in the code that was turning on channels by default. It got moved to an external function. This is happening in all modes
![Screen Shot 2019-11-07 at 11 06 01 AM](https://user-images.githubusercontent.com/25914123/68410605-978e8c80-014e-11ea-9b75-1aaefc1a7656.png)

**Comment by retiutut** [comment]
Fixed 🛠. Will be available again in 4.1.7-beta.1 ✅

**Comment by Otemo** [comment]
Hi retitutut:
Sorry for taking your time about the issue.
I appreciate your quick support.

**Comment by retiutut** [comment]
It's ok @Otemo. It's better to catch things like this quickly, so you did the right thing!
