### ISSUE TITLE
Is it possible to get recordings for the Band Pass and FFT information?

### ISSUE THREAD

**Issue by fawazsammani** [OpenBCI/OpenBCI_GUI#658]
Hi, this is not actually a problem. Just a question regarding the recordings:
1- Is it possible to get recordings for the Band Pass and FFT information?
2- Is the data recorded with the settings set in the GUI? (For example: filter settings) or is it the non-filtered data?

**Comment by retiutut** [comment]
The GUI always saves the RAW, unfiltered, data to file.  This allows you to playback the data and add any kind of filtering you like.

To stream FFT or BandPower data from a recording using the OpenBCI data format:
- Open the recording using Playback Mode
- Open the FFT and BandPower widgets
- Open the Networking Widget
- You can then stream the TimeSeries, FFT, and BandPower using either LSL, UDP, or OSC
