### ISSUE TITLE
Feature Request: Spectrogram Vertical Display

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#660]
**Is your feature request related to a problem? Please describe.**
No. This is an extension of #416 from @jps2000

**Describe the solution you'd like**
> L/R horizontally mirrored (In case you want / need to do it different to Masimo you can plot it vertically ( vertical time axis , widget format portrait, Then the power spectrum is growing from the bottom like a hourglass.) (Orientation dropdown)

**Describe alternatives you've considered**
Current horizontal solution is the default, so this would be adding an alternative display method.

**Additional context**
n/a

**Comment by jps2000** [comment]
Lets check / debug horizontal first!
