### ISSUE TITLE
JS with cyton wifi shield problem

### ISSUE THREAD

**Issue by gerardklee** [OpenBCI/OpenBCI_GUI#663]
Hi, I would appreciate any help! I will describe my problem below. I've attached my code and the image that shows the problem. In the image, I am referring to channel 1 (gray).
<img width="1019" alt="Screen Shot 2020-01-08 at 10 00 32 PM" src="https://user-images.githubusercontent.com/47463934/72042274-cfa37000-3262-11ea-9621-cb11fdab2828.png">
<img width="454" alt="Screen Shot 2020-01-08 at 10 01 03 PM" src="https://user-images.githubusercontent.com/47463934/72042282-d631e780-3262-11ea-9c3c-5349dbdf62d8.png">

## Problem
I am working on project with Javascript and cyton wifi shield. As soon as I start streaming from the board using LSL and run my javascript file on the terminal (I have a mac), the signals completely stop on the GUI. I am assuming they are supposed to be continuosly moving while streaming.

## Expected 

Signals keep moving forward on the GUI while streaming the signals from the board to print the values on the console.

## Operating System and Version

**macOS**/Windows/Linux
version 10.14.6

## GUI Version
version 4.1.5

## Running standalone app

I don't understand what standalone app is

## Type of OpenBCI Board

**Cyton**/Cyton+Daisy/Ganglion

## Are you using a WiFi Shield?

**Yes**/No

## Console Log

No console log. Signals completely stop (meaning they don't move forward).

**Comment by gerardklee** [comment]
I wanted to mention that streaming the data works perfectly fine with matlab. It is just in javascript, as soon as streaming begins, signals stop going.

**Comment by retiutut** [comment]
It looks like you are trying to connect to the board twice at the same. You would need to accept an LSL stream in Javascript, or you can connect directly to the board using Javascript.
