### ISSUE TITLE
Project: Integrate Brainflow - GUI v5

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#669]
## Problem

It's time to use a Java library for signal acquisition, and Brainflow will help us do that!

Java Package Install Instructions:

https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#java

Java API Reference:

https://brainflow.readthedocs.io/en/stable/UserAPI.html#java-api-reference

## Expected 

Get data from boards without running a separate app.

## Operating System and Version

All OS

## GUI Version

v4.1.7

## Running standalone app

Both Standalone and Processing-Java versions

## Type of OpenBCI Board

All OpenBCI Boards

## Are you using a WiFi Shield?

Includes WiFi board

## Console Log

N/A

**Comment by Andrey1994** [comment]
I think it also should be rewritten https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/DataProcessing.pde#L365
