### ISSUE TITLE
Feature Request: Simple Neurofeedback - assign tones to Band Power widget

### ISSUE THREAD

**Issue by professorderekdecker** [OpenBCI/OpenBCI_GUI#709]
I have the Ganglion and wish to practice changing brain states through meditation, concentration, etc.  However, in order to have biofeedback, I currently have to look at the OpenBCI GUI screen. This is not conducive to meditative relaxation. I ask that the 5 brain wave ranges each be assigned a note in a chord (the major 7th or other melodious combination). With eyes closed, I'll be able to listen to the notes and learn how best to change them (aka brain states). It may also be useful to impose a modulation (slower modulation on the lower notes for lower brain wave ranges). That way, if your mind drifts away from recognizing notes, it can hone in on the modulation. Also, for those interested in combining this with binaural beats, we may need a binaural beats generator and mixer (to combine the biofeedback and beats stimulation).

**Comment by professorderekdecker** [comment]
By the way, I did try neuromore but was unable to get the Ganglion to connect. If another sound generating biofeedback device or software works with the Ganglion, then please let me know. Thank you.

**Comment by retiutut** [comment]
You can try Brainflow + TimeFlux: https://doc.timeflux.io/latest/general/about.html

This is scheduled to be added to the OpenBCI docs.


Marking this issue as a new feature request! 😄

**Comment by retiutut** [comment]
More details here from similar issue: https://github.com/OpenBCI/OpenBCI_GUI/issues/745

**Comment by daniellasry** [comment]
Hey Derek, it sounds like the ideal scenario for you would be to get the Ganglion working with Neuromore.

Unfortunately I'm not very familiar with neuromore. It seems like they added Cyton support at some point, but not for Ganglion. Am I correct?

We have a fresh new API for OpenBCI Boards: brainflow. It can be used in Python, Java, R, C++, C#, Matlab, Julia. I see that neuromore is open source and based in C++. Maybe the neuromore devs would be open to integrating brainflow. IF they did, they would be adding support for all OpenBCI boards at once.

[brainflow source](https://github.com/OpenBCI/brainflow)
[documentation](https://brainflow.readthedocs.io/en/stable/)

**Comment by rakeshbci** [comment]
You can connect ganglion and cyton to neuromore using OSC proctocol. Stream the data from GUI to a python script and stream each channel to a specific OSC address.

**Comment by professorderekdecker** [comment]
Is there a video or website or pdf or anything that gives more detail about how to do this?

Thank you,
Derek

________________________________

**Comment by professorderekdecker** [comment]
I downloaded and tried neuromore again. The same behavior occurs. It will briefly connect to the Ganglion, then disconnect and won't reconnect. Very frustrating!

What is "OSC proctocol. Stream the data from GUI to a python script and stream each channel to a specific OSC address."? I have no idea what this means. How do I learn how to do this? Are there any examples I can download? Who has done this and how do I connect with them?

Derek
________________________________
