### ISSUE TITLE
Live data source not starting in Ganglion

### ISSUE THREAD

**Issue by SergDaut** [OpenBCI/OpenBCI_GUI#811]
## Problem

Hi my OPen BCI GUI is not starting unfortunately. I just received the electrodes and downloaded the OPen BCI GUI program. When i click on Start system nothing happens. I have ganglion board and dongle connected to my laptop. I followed all Getting started steps.

## Expected 

I expect the program to start working.

## Operating System and Version

Windows 32bit

## GUI Version

v3.3.2

## Running standalone app

Running the downloaded app

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here

**Comment by retiutut** [comment]
We are no longer supporting Windows 32bit operating systems. You can still use GUI v4.1.7, which has a published 32bit build.

https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v4.1.7

You also need to use a BLED112 dongle, as the CSR dongle is not supported. https://shop.openbci.com/collections/frontpage/products/ganglion-dongle
