### ISSUE TITLE
OpenBCI GUI v5.0 freeze at "Attempt to start session" upon Sample Data opening on two different MacOs Sierra. v4.2 work.

### ISSUE THREAD

**Issue by clemriedel** [OpenBCI/OpenBCI_GUI#830]
## Problem

OpenBCI GUI v5.0 freeze at "Attempt to start session" upon Sample Data opening on MacOs Sierra

## Expected 

To start the GUI. v4.2 worked for me

## Operating System and Version

macOS sierra 10.12.6

## GUI Version

5.0

## Running standalone app

Downloaded App

## Type of OpenBCI Board

No board, just playback

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here

**Comment by retiutut** [comment]
I think this is because we need to either convert the sample data or make new recordings that are compatible with GUI v5.

Thank you for making an issue!

**Comment by retiutut** [comment]
A fix for this issue has just been merged. Thank you for making this issue!
