### ISSUE TITLE
GUI freezes by selecting Spectrogram Widget

### ISSUE THREAD

**Issue by Otemo** [OpenBCI/OpenBCI_GUI#839]
## Problem
Selecting the Spectrogram Widget, **just after starting GUI**, cause  the GUI freezing. 
If i select the Spectrogram Widget after running data stream, the GUI will **Not** freeze.

## Expected 
the Spectrogram Widget can be selected, just after  starting GUI.

## Operating System and Version
Windows10

## GUI Version
GUI-5.0.0-beta.2

## Running standalone app
Running from Processing

## Type of OpenBCI Board
Ganglion

## Are you using a WiFi Shield?
No

## Console Log
Console Log Started at Local Time: 2020-07-24_19-29-18
Screen Resolution: 1920 X 1080
Welcome to the Processing-based OpenBCI GUI!
For more information, please visit: https://openbci.github.io/Documentation/docs/06Software/01-OpenBCISoftware/GUIDocs
TopNav: Internet Connection Not Available
Local GUI Version: 500
OpenBCI_GUI::Setup: Sample Data exists in Documents folder.
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
OpenBCI_GUI::Setup: Setup is complete!
sourceList: click! 
Channel count set to 4
[DEFAULT]: BLE Devices Refreshing
ControlPanel: Found BLED112 Dongle on COM port: COM3
bleList: click! 
[DEFAULT]: Ganglion Device Name = Ganglion-a630
[DEFAULT]: Attempting to Start Session...
initButtonPressed: Calling initSystem() after next draw()
OpenBCI_GUI: Start session. Calling initSystem().

||             INITIALIZING SYSTEM             ||

MAC address for Ganglion is c3:28:70:f4:82:ab
Sending config string to board: n
Channel count set to 4
InitSettings: Saving Default Settings to file!
SoftwareSettings: 4 active widgets saved!
[SUCCESS]: Session started!
headPlot: computeWeightFactor: Ielec 0, solution complete with 2000 iterations. max_dVal = 1.0759383E-5
headPlot: computeWeightFactor: Ielec 1, solution complete with 2000 iterations. max_dVal = 1.0493398E-5
headPlot: computeWeightFactor: Ielec 2, solution complete with 2000 iterations. max_dVal = 8.711815E-5
headPlot: computeWeightFactor: Ielec 3, solution complete with 2000 iterations. max_dVal = 8.860826E-5
New widget [8] selected for container...
Your cursor is in Ganglion Signal

![Processing](https://user-images.githubusercontent.com/38579786/88382852-4f022680-cde4-11ea-844c-40a53dbeeb3e.png)

**Comment by retiutut** [comment]
@Otemo I have merged a fix for this issue. Thank you for letting us know! 

We are hoping to release a stable version of GUI v5 very soon.

If you would like to use this change now, you can use the `development` branch.

 Take care!
-RW
