### ISSUE TITLE
Ch1 OSC time series data stream replaced with sample index (0-255 looping)

### ISSUE THREAD

**Issue by sksamuel0** [OpenBCI/OpenBCI_GUI#891]
## Problem

With version 4.2.0 the ch1 timeseries data appears normally when streaming over OSC. Upon switching to the new version all ch1 timeseries values are outputting sample index values.

## Expected 

Ch1 values should be the biopotential output values from ch1 visualized in the GUI similar to that of the other active channels.

## Operating System and Version

Windows

## GUI Version

v5.0.1

## Running standalone app

Running the downloaded app

## Type of OpenBCI Board

Cyton+Daisy

## Are you using a WiFi Shield?

Yes

## Console Log

Output data from 5.0.1 stream
{"cyton": {**"ch1": 86.0**, "ch2": -147119.015625, "ch3": -187500.015625, "ch4": -53347.48828125, "ch5": -168369.671875, "ch6": -167750.703125, "ch7": -187500.015625, "ch8": 187500.0, "ch9": 187500.0, "ch10": -187500.015625, "ch11": -187500.015625, "ch12": -187500.015625, "ch13": -187500.015625, "ch14": -187500.015625, "ch15": -187500.015625, "ch16": -187500.015625}

{"cyton": {**"ch1": 87.0**, "ch2": -147164.578125, "ch3": -187500.015625, "ch4": -53386.3125, "ch5": -168390.796875, "ch6": -167782.78125, "ch7": -187500.015625, "ch8": 187500.0, "ch9": 187500.0, "ch10": -187500.015625, "ch11": -18750........

**Comment by retiutut** [comment]
Yes, see #889.
