### ISSUE TITLE
BDF output format incorrectly encodes 24h time format

### ISSUE THREAD

**Issue by rivasd** [OpenBCI/OpenBCI_GUI#904]
## Problem

In v5 GUI, when choosing BDF output, the files have a 12h error on the recording start date (e.g. says 7h instead of 19h). This is visible both in latest MNE-Python and EDFBrowser

## Expected 

The current recording start time would be written in the .bdf file

## Operating System and Version

Windows 10 

## GUI Version

5.0.1

## Running standalone app

Standalone

## Type of OpenBCI Board

Cyton+Daisy 16 channels

## Are you using a WiFi Shield?

No

## Console Log

N/A

![image](https://user-images.githubusercontent.com/13322789/97917745-f3b8cc00-1d22-11eb-8541-94a4019810b1.png)
 You can see here that the file name has the current start time (around 7PM) but the time reported by EDFBrowser is 7AM

**Comment by retiutut** [comment]
@rivasd Thank you for being a valued Community member. I will look into this. It looks like you have included enough information to replicate this issue.

Marking this as high priority and possibly easy fix.

**Comment by retiutut** [comment]
https://stackoverflow.com/a/21565579

**Comment by retiutut** [comment]
![GUI bdf 24hr timestamp fix - nov 2020](https://user-images.githubusercontent.com/25914123/98425017-4fec5a80-2059-11eb-89d5-1cf41bb07af0.PNG)

**Comment by retiutut** [comment]
The above fix will be included in 5.0.2. Thank you for creating this issue!
