### ISSUE TITLE
Data Log option is missing in GUI

### ISSUE THREAD

**Issue by Sarthak031** [OpenBCI/OpenBCI_GUI#921]
Hi There,
I am not able to find the data log option in the openBCI GUI application if it exists, please provide me how to log the EEG data.

**Comment by retiutut** [comment]
>By default, the GUI stores all user data and raw EEG recordings in Documents/OpenBCI_GUI and names each session with an autogenerated timestamp by default.

https://docs.openbci.com/docs/06Software/01-OpenBCISoftware/GUIDocs#using-the-openbci-gui

**Comment by retiutut** [comment]
I think we can add a new section to the main GUI doc that clearly states this information. Thank you for making this issue!
