### ISSUE TITLE
Gifanimation library is not available for the newest processing (or on linux)

### ISSUE THREAD

**Issue by cfausn** [OpenBCI/OpenBCI_GUI#93]
I'm not able to run the newest development code with the gifanimation library, could be because i'm using linux or could be because the library is deprecated.

**Comment by aj-ptw** [comment]
It's in the libraries folder, just gotta go drag and drop it into your sketch book folder!

**Comment by cfausn** [comment]
Okay, just so you know the "add library" option in processing does mention it is deprecated though. Just for future reference, could be confusing for users.

**Comment by aj-ptw** [comment]
Ok I'm gonna assign this to Conor! Thanks for the report, that could be confusing.
