### ISSUE TITLE
mouse location error when maximize the main windows of openbci_gui

### ISSUE THREAD

**Issue by hosseinaghaie** [OpenBCI/OpenBCI_GUI#935]
## Problem
mouse location error when maximize the main windows of openbci_gui

Explain the problem
when i maximize the openbci_gui ,the location of mouse over is upper than real mouse location.in fact in the maximum  size windows, when i want to select CYTON(LIVE) in DATASOURCE,we must move mouse on GANGLION(LIVE)
![e44b9bbb-af07-48e8-95a3-563b86d2a445](https://user-images.githubusercontent.com/19975480/102006309-6e6b0300-3d35-11eb-8858-0d8499768612.jpg)

## Expected 
In a perfect world, what do you expect to happen.

## Operating System and Version
windows 7,10

## GUI Version
5.0.1
## Running standalone app
yes
Are you running the downloaded app or are you running from Processing or Visual Studio Code?
processing 
## Type of OpenBCI Board
Cyton/Cyton+Daisy
## Are you using a WiFi Shield?
Yes

## Console Log

Paste any relevant text from the console window here

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/issues/900

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/pull/909
