### ISSUE TITLE
Allow Copy/Paste in session name field

### ISSUE THREAD

**Issue by BaggioMarco** [OpenBCI/OpenBCI_GUI#940]
Dear,

at the moment the session name field doesn't allow copy/paste. Could you please add this feature? You know, many times the participant ID is quite complex and now it has to be written entirely, while it could be copied from other sources and then pasted inside the GUI. Thank you!

**Comment by retiutut** [comment]
Not entirely sure this is possible. Involves ControlP5 textfield object. Copy/Pasting in Java is doable:

https://forum.processing.org/one/topic/copy-and-paste.html#25080000001711515.html

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/tree/copy-past-textfield-test

**Comment by retiutut** [comment]
Seems possible!!!!

Need to differentiate for OS.

- Mac == Command + V
- Linux == Control + Shift + V
- Windows == Control + V

**Comment by BaggioMarco** [comment]
Hi @retiutut that's a great news! 
If I update now from the master branch will I get this feature, or I've to download this one here https://github.com/OpenBCI/OpenBCI_GUI/tree/copy-past-textfield-test ???
In case, when this feature will be available in the master branch? thank you

**Comment by retiutut** [comment]
@BaggioMarco https://github.com/OpenBCI/OpenBCI_GUI/milestone/8

You will see the commits here that directly resolve this issue.

You're welcome! 😄 👍

**Comment by BaggioMarco** [comment]
Awesome! Thank you!

**Comment by retiutut** [comment]
![Uploading Screen Shot 2021-03-16 at 9.20.05 PM.png…]()

**Comment by retiutut** [comment]
![Screen Shot 2021-03-16 at 9 20 05 PM](https://user-images.githubusercontent.com/25914123/111405132-f5fe4000-869d-11eb-9da0-91ec3ab7ea77.png)
