### ISSUE TITLE
GUI V5.0.3 cannot connect to Cyton via USB adapter (Not RFDuino Dongle)

### ISSUE THREAD

**Issue by Hal6A** [OpenBCI/OpenBCI_GUI#958]
## Problem
My Cyton is connected to the PC via a USB wire, not RFDuino Dongle.
Now I'm trying to use GUI v5.0.3 to replace the old v4.2.0. The new version of GUI cannot read my COM port so I made some modification like this 

https://openbci.com/forum/index.php?p=/discussion/2708/openbci-gui-5-0-serial-port
![image](https://user-images.githubusercontent.com/80676378/111131163-dec13480-856f-11eb-9675-9b285aded043.png)

After the modification the GUI is able to read my COM port but it still shows error when I try to connect.
![image](https://user-images.githubusercontent.com/80676378/111131327-103a0000-8570-11eb-91cf-d2f933d485c0.png)

There is no error like this in 4.2.0 so I'm quite confused.

## Expected 

The GUI can connect to the Cyton.

## Operating System and Version

Windows 10 x64

## GUI Version

V5.0.3

## Running standalone app

Processing

## Type of OpenBCI Board

Cyton (3.1.1)

## Are you using a WiFi Shield?

No

## Console Log

[DEFAULT]: Attempting to open Serial/COM port: COM3
Radios_Config: connect_to_portName: Attempting to open serial port: COM3
Radios_Config: connect_to_portName: Port is open!
Radios_Config: Error reading from Serial/COM port

**Comment by retiutut** [comment]
https://openbci.com/forum/index.php?p=/discussion/2708/openbci-gui-5-0-serial-port

My comments here are still valid.
