### ISSUE TITLE
OpenBCI GUI v5.06 opens blank screen - macOS Catalina

### ISSUE THREAD

**Issue by Daisykh** [OpenBCI/OpenBCI_GUI#990]
## Problem

When updated from 5.05 to 5.06, the OpenBCI GUI fails to open and displays a blank grey screen. v5.05 opens as expected with full functionality to connect to a Cyton board. I have tried 3 times to update and each time have had the same issue with 5.06 causing me to uninstall and reinstall 5.05. Image of GUI with version number below:
![image](https://user-images.githubusercontent.com/29408184/130103196-584cd5be-13dd-4946-ad39-eb53e4bb4034.png)

## Expected 

Opening the app should display the GUI as it does with 5.05. Image of previous version working below:
![image](https://user-images.githubusercontent.com/29408184/130103722-df55661c-633d-465d-acc6-622d383c565a.png)

## Operating System and Version

macOS Catalina, v10.15.7
Macbook Pro 2019

## GUI Version

5.06
## Running standalone app

Downloaded GUI app
## Type of OpenBCI Board

Cyton board

## Are you using a WiFi Shield?

No

## Console Log

n/a, console log doesn't appear

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/issues/987

This is likely a duplicate issue that will have a fix in the next version of the GUI. To confirm, you could follow the same steps as in the other thread.

**Comment by Daisykh** [comment]
Ahh! Yes, looks like the same issue even though I'm on an intel macbook pro and not M1! Here's the results:

1. Running via processing3, no changes made and results in the blank screen. Here's the console output:
![image](https://user-images.githubusercontent.com/29408184/130108867-f139fa81-ea1c-4152-9a48-0a7501804c39.png)

2. Commented out `pixelDensity` and it now opens! Here's the console log output that includes the screen size and High-DPI detection of my macbook:
![image](https://user-images.githubusercontent.com/29408184/130109230-3a059db8-1a08-4389-9ca4-2e7060d323b5.png)

3. I also tried moving `pixelDensity(displayDensity())` into the `settings` function and it produced the same results as commenting it out entirely. Here's a screen grab:
![image](https://user-images.githubusercontent.com/29408184/130110201-f9e8974e-49b7-433b-8030-fb2c2e364730.png)

This issue can be closed as a duplicate and I can relay my findings in #987 if it would be helpful.

**Comment by retiutut** [comment]
Since this happened on different hardware and OS version, I'm going to keep this open until it's fixed.

Thank you for making an issue and following the template!
